//! DPVO's patch bundle adjustment (`fastba.BA`) — Milestone M3 of
//! `docs/dpvo_droid_port_plan.md`.
//!
//! Read that plan doc's "M1 results" and "M2 results" sections before
//! touching this module; they record the fixture provenance (`ba_fixture.npz`
//! at `E:/visloc_archive/dpvo_onnx_m1/fixtures/`, generated by
//! `scripts/export_dpvo_onnx.py`'s `dump_ba_fixture`/`mini_ba`/`MiniSE3`) and
//! why the pure-PyTorch reference had to be hand-copied rather than imported.
//!
//! # Ground truth and what was ported from where
//!
//! The **only** ground truth for this module's math is
//! `E:/tools/DPVO/dpvo/ba.py`'s `BA()` function (lines 86–182) — DPVO's own
//! pure-PyTorch reference implementation, used whenever the CUDA `fastba`
//! extension is unavailable — together with `projective_ops.py`'s
//! `transform()` (lines 53–113), whose analytic Jacobians `BA()` consumes.
//! `scripts/export_dpvo_onnx.py`'s `mini_ba`/`pops_transform`/`MiniSE3` (lines
//! 352–667) are a *from-scratch* SE3 stand-in for `dpvo.lietorch.SE3` (needed
//! because `lietorch`'s compiled CPU/GPU extension is not built on this
//! machine) wrapped around the **same** copied Gauss-Newton/Schur-complement
//! arithmetic; `dump_ba_fixture` (lines 670–757) is what produced
//! `ba_fixture.npz`. Every formula below cites the upstream line range it
//! reproduces so a future reader can diff against the real files rather than
//! trust this comment.
//!
//! # Placement: a new module, not `bundle.rs`
//!
//! The plan doc's §4 port-surface table (written before M1/M2 ran) floated
//! folding patch inverse-depth into `bundle.rs`'s existing
//! [`crate::bundle::BundleAdjustment`] as one more residual/variable kind.
//! Having now read `ba.py` line by line, that would be the wrong shape of
//! reuse: `BundleAdjustment` runs an open-ended Levenberg-Marquardt loop
//! (adaptive `λ`, cost-based accept/reject, convergence checks) over
//! `Point3<f64>` landmarks with a **right**-perturbation pose convention
//! (`T ← T · Exp(ξ)`, see `bundle.rs`'s own module doc). `fastba.BA` is a
//! completely different animal: a **fixed two-call** Gauss-Newton with no
//! line search, a scalar (not 3-DoF) inverse-depth patch variable, its own
//! three-part damping scheme (`lmbda`/`ep`/a hardcoded `lm=1e-4`, see below),
//! its own hard-gating validity mask (no Huber — see "Robustness" below), and
//! a **left**-perturbation pose convention (`T ← Exp(ξ) · T`, matching
//! `lietorch`). Splicing that into `BundleAdjustment`'s loop would either
//! silently change `ba.py`'s semantics to fit the host loop, or bolt a second
//! incompatible perturbation convention onto one struct — both worse than a
//! small, self-contained, exactly-cited sibling module. This module reuses
//! `bundle.rs`'s *spirit* (Schur-eliminate the per-landmark/per-patch block,
//! solve a dense pose-only system, back-substitute) and
//! `visloc_core::geometry::SE3` directly (`compose`/`inverse`/`exp`/`adjoint`/
//! `matrix`, no core changes needed — see "Convention mapping" below), but
//! keeps its own damping/iteration/gating logic so a reader can diff it
//! against `ba.py` without first subtracting out `BundleAdjustment`'s
//! unrelated LM machinery. It lives in `pipelines/slam/src` (not a
//! `dpvo`-prefixed module in `crates/vision`) precisely because it is pure
//! `nalgebra` math with **no** `ort`/ONNX dependency — the task's own
//! constraint ("must NOT be gated behind `onnx-inference`") and
//! `visloc-slam`'s `Cargo.toml` (no `onnx-inference` feature anywhere in this
//! crate) make that the natural home; `crates/vision/src/dpvo` stays the
//! ONNX/native-inference layer M2 built, entirely unrelated to this module
//! except by sharing the same upstream repo. No pipeline wiring, sliding
//! window, or patch lifecycle is added here — that is M4's scope, per the
//! task brief.
//!
//! # Convention mapping (DPVO/lietorch ⇄ `visloc_core::geometry::SE3`)
//!
//! DPVO's `poses` tensor is `(batch, n_frames, 7)`, each row
//! `[tx, ty, tz, qx, qy, qz, qw]` — translation then an **xyzw** unit
//! quaternion (`MiniSE3.__init__`'s own comment, `export_dpvo_onnx.py:369`).
//! [`se3_from_dpvo_pose`]/[`dpvo_pose_from_se3`] are the exact boundary
//! conversion: `visloc_core::geometry::SE3::new(rotation, translation)` takes
//! a `nalgebra::UnitQuaternion<f64>`, and this codebase's own established
//! idiom for xyzw→nalgebra construction (`Quaternion::new(qw, qx, qy, qz)`,
//! e.g. `pipelines/slam/src/g2o.rs:215`, `crates/io/src/euroc.rs:219`) is
//! reused verbatim here — no reordering bug to introduce.
//!
//! Each DPVO pose is `T_world_to_camera` for its frame — confirmed from
//! `MiniSE3`'s own docstring ("world-to-camera convention: acting on a point
//! maps world/source-frame coordinates into this pose's frame",
//! `export_dpvo_onnx.py:353`) and from how `ba.py`/`pops_transform` compose
//! them: `Gij = poses[jj] * poses[ii].inv()` maps a point already expressed
//! in camera-`i` coordinates into camera-`j` coordinates, which only
//! type-checks if `poses[ii].inv()` sends camera-`i` points to world and
//! `poses[jj]` sends world points to camera-`j`. That is exactly
//! `visloc_core::geometry::Pose::world_to_camera`'s own meaning, so this
//! module's `poses: Vec<SE3>` field needs no semantic translation — only the
//! numeric xyzw/wxyz boundary above.
//!
//! Composition: `MiniSE3.mul(self, other)` computes `self ∘ other`
//! (`export_dpvo_onnx.py:430-434`: rotate `other`'s translation by `self`'s
//! rotation, then add `self`'s translation) — **exactly**
//! [`SE3::compose`]'s own formula (`crates/core/src/geometry/se3.rs:32-37`).
//! `ba.py:60`'s `Gij = poses[:, jj] * poses[:, ii].inv()` therefore ports
//! directly as `poses[jj].compose(&poses[ii].inverse())`.
//!
//! Retraction: `MiniSE3`'s own docstring states the "LEFT perturbation
//! convention (`retr(a) = Exp(a) * X`) matching lietorch"
//! (`export_dpvo_onnx.py:356`), and `mini_ba`'s pose-update loop
//! (`export_dpvo_onnx.py:663-665`) computes exactly
//! `delta = MiniSE3.exp(xi); poses_out[i] = delta.mul(cur)` — i.e.
//! `Exp(ξ) ∘ T`, delta on the **left**. This is the opposite convention from
//! `bundle.rs`'s landmark BA (`T ← T · Exp(ξ)`, right perturbation) — a
//! deliberate, documented difference, not an inconsistency to reconcile: this
//! module ports `fastba.BA`'s own convention exactly, using
//! `SE3::exp(&dx).compose(&pose)` (delta-on-the-left) wherever `ba.py`
//! retracts a pose.
//!
//! Tangent layout: DPVO's `xi = (rho[3], phi[3])` (translation-first, then
//! rotation, `export_dpvo_onnx.py:411-422`) is **the same order** as
//! [`SE3::exp`]/[`SE3::log`]'s own `Vector6` layout (`[ρ; ω]`,
//! `crates/core/src/geometry/se3.rs:56-82`) — no column permutation needed
//! when reading `dX` blocks off the solved linear system straight into
//! `SE3::exp`.
//!
//! Adjoint: `MiniSE3.adjoint()` (`export_dpvo_onnx.py:461-475`) builds
//! `[[R, [t]×R], [0, R]]` for tangent order `(ρ, φ)` — **bit-for-bit the same
//! block formula** as [`SE3::adjoint`] (`crates/core/src/geometry/se3.rs:86-94`,
//! doc-commented there as `Ad(T) = [[R, [t]× R], [0, R]]`). So `Gij.adjT(a)`
//! (`= a @ Ad(Gij)`, `export_dpvo_onnx.py:477-480`) ports directly as
//! `a * g_ij.adjoint()` with **no new core method** — this module is the
//! concrete confirmation of the plan doc's §5 M3 note that "Reuse
//! `visloc_core::geometry`" would need no new SE3/SO3 method.
//!
//! # The projective transform and its Jacobians (`projective_ops.py:53-113`)
//!
//! A patch is anchored at pixel `(x, y)` in some frame `i` with inverse depth
//! `d`. `iproj` (`projective_ops.py:19-29`) backprojects it to the
//! **unnormalized homogeneous** 4-vector `X0 = (xn, yn, 1, d)` where
//! `xn = (x - cx_i)/fx_i`, `yn = (y - cy_i)/fy_i` — note the third component
//! is the constant `1`, *not* metric depth; `d` (inverse depth) is carried as
//! the trailing "homogeneous weight" component `W`, not multiplied in yet.
//! `SE3`'s action on this generalized point (`act4`,
//! `export_dpvo_onnx.py:446-451`) is `(X,Y,Z,W) ↦ (R·(X,Y,Z) + t·W, W)`: the
//! numerator transforms rigidly, scaling the translation contribution by `W`,
//! while `W` itself is invariant. This is the standard trick that makes the
//! *actual* 3D point `(X,Y,Z)/W` transform correctly under a rigid motion
//! while keeping the patch's inverse depth as an ordinary carried-through
//! scalar (self-consistent: `T(p) = R·(X,Y,Z)/W + t = (R·(X,Y,Z) + t·W)/W`).
//! `proj` (`projective_ops.py:32-50`) then perspective-divides by the
//! transformed **Z** (not `W` — the ratio `X/Z` is invariant to the shared
//! `W` scaling, so this is equivalent), giving the reprojected pixel
//! `(fx_j · X/Z + cx_j, fy_j · Y/Z + cy_j)`.
//!
//! The analytic Jacobians (`projective_ops.py:71-108`, reproduced verbatim in
//! `export_dpvo_onnx.py:517-539`) are evaluated **only at the patch's center
//! pixel** — DPVO patches are `3×3` grids sharing one `(x, y, d)` triple
//! (confirmed by `dump_ba_fixture`'s fixture construction,
//! `export_dpvo_onnx.py:686-692`, which broadcasts the same scalar across the
//! whole `P×P` block), so this module's [`DpvoPatch`] stores just that one
//! triple — the `3×3` replica the fixture's `.npz` carries is a
//! correlation-lookup artifact (M2's `patchify`/`corr_cpu` concern), not a BA
//! input; the fixture *loader* (in the `#[ignore]`-gated parity test, not
//! this module) asserts the replica is uniform before discarding it, so
//! nothing is silently dropped:
//!
//! * `Ja` (`4×6`): `∂X1/∂ξ_j` at the center pixel, `projective_ops.py:83-88`.
//! * `Jp` (`2×4`): `∂proj/∂X1`, using `d = 1/Z` only where `|Z| > 0.2`
//!   (else `0`, `projective_ops.py:79-80` — a divide-by-zero guard for the
//!   Jacobian only, distinct from the separate `Z > 0.2` *validity* mask
//!   below).
//! * `Jj = Jp · Ja` (`2×6`).
//! * `Ji = -Gij.adjT(Jj) = -(Jj · Ad(Gij))` (`2×6`) — the chain-rule term for
//!   perturbing `pose_i` through `Gij = Pj · Pi⁻¹`.
//! * `Jz = Jp · Gij.matrix()[:, 3:]` (`2×1`) — sensitivity to the patch's
//!   scalar inverse depth (the last column of `Gij`'s `4×4` homogeneous
//!   matrix is `[tx, ty, tz, 1]ᵀ`).
//!
//! # Robustness: hard gates, **not** Huber (`ba.py:96-112`)
//!
//! `ba.py`'s `BA()` has **no smooth robust kernel anywhere** — confirmed by
//! reading the whole function; there is no `.abs().clamp()`-style Huber loss,
//! only three independent `0`/`1` multiplicative gates on the per-edge
//! residual/weight before they enter the normal equations:
//!
//! 1. `Z > 0.2` at the center pixel (not `|Z|`, matching `projective_ops.py`'s
//!    own `valid` return, distinct from the Jacobian's `|Z| > 0.2` guard
//!    above).
//! 2. `‖target − coords‖ < 250` px (`ba.py:98`) — a fixed outlier-rejection
//!    radius, not adaptive.
//! 3. The *predicted* (uncorrected) pixel lies within `bounds =
//!    [x0, y0, x1, y1]` (`ba.py:100-106`) — a visibility gate on the
//!    reprojection, not on the target.
//!
//! An edge failing any gate has its residual **and** its learned 2-channel
//! weight zeroed (`ba.py:111-112`) before any product is formed, so it
//! contributes exactly nothing to `B`/`E`/`v`/`w` — this module ports that
//! zeroing, not a Huber weight, per the task's explicit "only if the
//! reference has it" instruction.
//!
//! # Damping: three distinct constants, easy to conflate (`ba.py:86, 158, 169`)
//!
//! `BA(..., lmbda, ..., ep=100.0, ...)` — three *different* damping terms
//! hide behind similar names:
//!
//! 1. **`lmbda`** (a `BA()` call argument, [`DpvoBaConfig::lmbda`] here): a
//!    Tikhonov term added to the scalar per-patch depth Hessian before
//!    inverting, `Q = 1 / (C + lmbda)` (`ba.py:158`). `dpvo.py`'s real call
//!    sites always pass a scalar `1e-4` (`dpvo.py:322, 338`); `ba.py` also
//!    accepts a per-patch tensor via `.reshape(*C.shape)` broadcasting, which
//!    no real call site exercises — this port implements only the scalar
//!    form, honestly narrower than upstream's generic (but dead) code path.
//! 2. **`ep`** (`BA()`'s own default `100.0`, [`DpvoBaConfig::ep`] here): a
//!    flat additive term on the pose-block's *diagonal* only, added inside
//!    `block_solve` (`ba.py:73`, `S[d,d] ← S[d,d]·(1+lm) + ep`).
//! 3. **`lm = 1e-4`** (`POSE_DIAG_LM` here): `block_solve`'s own hardcoded
//!    default argument (`ba.py:66`) — a Levenberg-Marquardt-style
//!    multiplicative diagonal scale, **never exposed** as a `BA()` parameter
//!    at all. Note `block_solve`'s damping line, read literally, is
//!    `A + (ep + lm·A) * eye(n)`: `(ep + lm·A)` is a full matrix (broadcasting
//!    the scalar `ep`), and the elementwise (Hadamard) product with `eye(n)`
//!    zeroes everything off the diagonal while keeping `ep + lm·A[d,d]` on
//!    it — i.e. `A[d,d] ← A[d,d]·(1 + lm) + ep`, off-diagonals untouched.
//!    This module ports that exact per-scalar-diagonal formula, not a
//!    per-6×6-block or uniform-λI damping.
//!
//! # Iteration count: `BA()` is ONE Gauss-Newton step; "2 iterations" is the
//! caller's loop (`dpvo.py:325, 354`)
//!
//! `ba.py`'s `BA()` linearizes once (one call to `pops.transform`), solves
//! once, retracts once, and returns — it has no internal loop. The "2
//! Gauss-Newton iterations" the plan doc's M1 results attribute to
//! `fastba.BA` is an argument (`iterations=2`) to the **compiled CUDA**
//! extension's entry point (`dpvo.py:325, 354`), which is *not* the pure
//! Python reference this task ports; the pure reference achieves the same
//! effect by the *caller* invoking `BA()`/`mini_ba` twice in a row, feeding
//! iteration 1's output poses/patches into iteration 2 with the **same**
//! `target`/`weight`/`lmbda` (re-linearizing at the new state each time) —
//! confirmed directly in `dump_ba_fixture`'s own fixture generation
//! (`export_dpvo_onnx.py:745-746`: `mini_ba` called twice, feeding
//! `poses_1, patches_1` into the second call). [`dpvo_ba_step`] here is one
//! such call (`ba.py`'s whole `BA()` body); [`dpvo_ba`] is the two-call (or
//! `config.iterations`-call) outer loop.
//!
//! # `t0` / `fixedp`: the first `fixedp` poses are gauge-fixed, but their
//! patches are not (`ba.py:129-135, 140-153`)
//!
//! `dpvo.py` calls the real extension with a `t0` argument (`dpvo.py:325,
//! 354`); the pure-Python reference's matching parameter is named `fixedp`
//! (default `1`, `ba.py:86`). Poses at index `< fixedp` are excluded from the
//! variable index space entirely (`ii, jj ← ii − fixedp, jj − fixedp`,
//! `n ← n − fixedp`, `ba.py:130-135`) — they are not "damped hard", they are
//! simply not columns in the linear system, so no gradient/Hessian
//! contribution referencing them is even well-typed. Critically, this
//! **only** removes their contribution to the *pose* Hessian/gradient/cross
//! term (`safe_scatter_add_mat`/`safe_scatter_add_vec` on `ii`/`jj` after the
//! `− fixedp` shift, `ba.py:140-151`); the scalar per-patch terms `C`/`w`
//! (`ba.py:148, 153`) are accumulated via `pure_scatter_sum`/`safe_scatter_add_vec`
//! keyed only on `kk` (never on `ii`/`jj`), so an edge anchored at a fixed
//! pose still contributes its full evidence to that patch's depth update.
//! `n2 == 0` (every pose fixed, `ba.py:163`, mirrored as
//! `structure_only`'s branch) skips the Schur solve and pose retraction
//! entirely and sets `dZ = Q · w` directly — this module's requirement-4 test
//! (["depth-only update when all poses fixed"](tests)) exercises exactly this
//! branch.
//!
//! # Fixture parity target
//!
//! `E:/visloc_archive/dpvo_onnx_m1/fixtures/ba_fixture.npz`: 3 frames, 2
//! patches, 4 edges, `fixedp = 1`, `ep = 100.0` (default, not overridden by
//! `dump_ba_fixture`), `lmbda = 1e-4`, 2 chained Gauss-Newton iterations.
//! Inspected directly (`E:/tools/venvs/dpvo_export/Scripts/python.exe`,
//! `numpy.load`): `poses_in (1,3,7) f32`, `patches_in (1,2,3,3,3) f32`,
//! `intrinsics (1,3,4) f32`, `target (1,4,2) f32`, `weight (1,4,2) f32`,
//! `lmbda () f32`, `ii/jj/kk (4,) i64`, `bounds (4,) f32`,
//! `poses_after_iter1/2 (1,3,7) f32`, `patches_after_iter1/2 (1,2,3,3,3) f32`.
//! All present; no fixture extension was needed (contrast M1/M2, which each
//! found a gap requiring `export_dpvo_onnx.py` changes) — every input `BA()`
//! needs was already dumped. See `crates/../tests/dpvo_patch_ba_fixture.rs`
//! for the loader and parity numbers, and the plan doc's "M3 results" section
//! for the final measured max-abs-diff.

use nalgebra::{DMatrix, DVector, Matrix6, Quaternion, SMatrix, UnitQuaternion, Vector2, Vector3};
use visloc_core::geometry::SE3;

/// `block_solve`'s hardcoded multiplicative diagonal damping (`ba.py:66`'s
/// default `lm=1e-4`), **never** exposed as a `BA()` parameter — see the
/// module doc's "Damping" section, constant 3.
///
/// `pub(crate)`: reused by [`crate::dpvo_vi_ba`] (Milestone M5), which applies
/// the *same* pose-diagonal damping formula to the visual+IMU combined pose
/// Hessian block rather than inventing a second damping constant — see that
/// module's doc for why sharing this constant (not just the formula) matters.
pub(crate) const POSE_DIAG_LM: f64 = 1e-4;

/// Outlier-rejection residual-norm gate, `ba.py:98`: `r.norm(dim=-1) < 250`.
const RESIDUAL_NORM_GATE_PX: f64 = 250.0;

/// `proj`'s divide-by-zero guard on the perspective divide itself
/// (`projective_ops.py:43`: `d = 1.0 / Z.clamp(min=0.1)`), independent of the
/// Jacobian's own `|Z| > 0.2` guard and the residual-gating `Z > 0.2` mask.
const PROJECT_MIN_Z: f64 = 0.1;

/// Jacobian divide-by-zero guard (`projective_ops.py:79-80`):
/// `d[Z.abs() > 0.2] = 1/Z`, else `0`.
const JACOBIAN_MIN_ABS_Z: f64 = 0.2;

/// Residual-validity threshold on the (non-absolute) transformed `Z`
/// (`projective_ops.py:108`: `(Z > 0.2).float()`).
const VALID_Z_THRESH: f64 = 0.2;

/// Inverse-depth clamp after retraction (`ba.py:176`:
/// `disps.clamp(min=1e-3, max=10.0)`).
///
/// `pub(crate)`: [`crate::dpvo_vi_ba`] (Milestone M5) re-clamps patches with
/// the identical bounds after its own (visual+IMU) retraction step.
pub(crate) const DISP_MIN: f64 = 1e-3;
pub(crate) const DISP_MAX: f64 = 10.0;

/// Per-frame pinhole intrinsics, matching `projective_ops.py`'s
/// `extract_intrinsics` unpacking order `(fx, fy, cx, cy)`.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct DpvoIntrinsics {
    pub fx: f64,
    pub fy: f64,
    pub cx: f64,
    pub cy: f64,
}

/// One patch's bundle-adjustment state: an anchor pixel `(x, y)` in its edges'
/// `ii`-frame, plus the scalar inverse depth `d` that this module's [`dpvo_ba`]
/// actually solves for. See the module doc's "projective transform" section
/// for why the `3×3` patch grid DPVO carries elsewhere collapses to this one
/// triple for BA purposes.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct DpvoPatch {
    pub x: f64,
    pub y: f64,
    pub inverse_depth: f64,
}

/// One patch-graph edge: patch `k` (anchored/backprojected in frame `i`'s
/// intrinsics) observed/reprojected into frame `j`. Matches `ba.py`'s
/// `(ii, jj, kk)` triplet arrays, one entry per edge.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct DpvoEdge {
    pub i: usize,
    pub j: usize,
    pub k: usize,
}

/// One `dpvo_ba`/`dpvo_ba_step` call's full input: poses, patches,
/// intrinsics, the patch-graph edges, and the learned per-edge
/// target-pixel/weight pair that `ba.py`'s `BA()` takes as `targets`/
/// `weights`. `targets`/`weights`/`edges` are indexed in lockstep (index `e`
/// is edge `e`'s data), matching upstream's parallel-array convention.
#[derive(Debug, Clone, PartialEq)]
pub struct DpvoBaProblem {
    /// `poses[f]` is frame `f`'s `T_world_to_camera` (see the module doc's
    /// convention-mapping section). Frame count `n_frames = poses.len()`; the
    /// upstream reference derives `n` from `max(ii, jj) + 1`, which coincides
    /// with `poses.len()` whenever every declared frame is referenced by at
    /// least one edge (true of `ba_fixture.npz` and of every test in this
    /// module) — a documented simplification, not a silent behavior change.
    pub poses: Vec<SE3>,
    pub patches: Vec<DpvoPatch>,
    /// `intrinsics[f]` is frame `f`'s pinhole intrinsics.
    pub intrinsics: Vec<DpvoIntrinsics>,
    pub edges: Vec<DpvoEdge>,
    /// Per-edge learned target pixel (`ba.py`'s `targets`), same length/order
    /// as `edges`.
    pub targets: Vec<Vector2<f64>>,
    /// Per-edge learned 2-channel confidence (`ba.py`'s `weights`) — **not**
    /// a scalar: the `u`/`v` reprojection channels get independently scaled,
    /// so this is a diagonal (not isotropic) per-edge information matrix
    /// `diag(w_u, w_v)`.
    pub weights: Vec<Vector2<f64>>,
    /// Milestone M15 (`docs/dpvo_droid_port_plan.md`, "depth-trust damping"):
    /// optional per-patch multiplier on [`DpvoBaConfig::lmbda`] for that
    /// patch's own depth-channel Tikhonov term. `None` — every prior
    /// milestone's construction, and every call site that does not opt in —
    /// means every patch's multiplier is `1.0`, reproducing `q = 1/(C +
    /// lmbda)` (`ba.py:158`) byte-for-byte. When `Some`, must be
    /// `patches.len()` long (indexed by the SAME global patch index
    /// `patches`/edges use, not a compacted "used patches" index — see
    /// [`dpvo_ba_step`]'s own "Depth damping" section for exactly where this
    /// is consulted); entry `k`'s value replaces the implicit `1.0` in
    /// `q[k] = 1/(C[k] + lmbda * depth_damping[k])`. A value `> 1.0` pulls
    /// that patch's depth update toward zero (i.e. trusts its CURRENT value
    /// more, since a low-parallax patch's own Jacobian information `C[k]` is
    /// near-zero, `q[k]` is dominated by the `lmbda` floor, not by real
    /// visual evidence — inflating that floor directly counters the
    /// unconstrained-depth explosion `docs/dpvo_droid_port_plan.md`'s "M13
    /// results" diagnosed). Left un-consulted (and therefore free) whenever
    /// `None` — no extra allocation, no extra branch inside the per-edge
    /// accumulation loop, only one extra lookup per LOCAL (used) patch when
    /// building `q` itself.
    pub depth_damping: Option<Vec<f64>>,
}

/// Configuration matching `BA()`'s remaining call arguments
/// (`ba.py:86`) — see the module doc's "Damping" and "`t0`/`fixedp`" sections
/// for what each knob means and where it is/isn't exposed upstream.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct DpvoBaConfig {
    /// Outer-loop call count (`dpvo.py`'s `iterations=2` argument to the real
    /// CUDA extension; the pure-Python reference achieves the same effect by
    /// calling `BA()` this many times in a row — see the module doc). DPVO's
    /// own call sites always use `2`.
    pub iterations: usize,
    /// Number of leading (lowest-index) poses excluded from the pose Hessian
    /// entirely (`ba.py`'s `fixedp`, `dpvo.py`'s `t0`). Their patches are
    /// still updated from edges anchored at them — see the module doc.
    pub fixedp: usize,
    /// Depth-channel Tikhonov term, `Q = 1/(C + lmbda)` (`ba.py:158`). Real
    /// call sites always use `1e-4`.
    pub lmbda: f64,
    /// Pose-block flat additive diagonal damping (`ba.py`'s `ep`, default
    /// `100.0`).
    pub ep: f64,
    /// Target-frame visibility gate `[x0, y0, x1, y1]` on the *predicted*
    /// (uncorrected) reprojected pixel (`ba.py`'s `bounds`).
    pub bounds: [f64; 4],
}

impl Default for DpvoBaConfig {
    /// `iterations = 2` (DPVO's own steady-state call, `dpvo.py:354`),
    /// `fixedp = 1` and `ep = 100.0` (`BA()`'s own defaults, `ba.py:86`),
    /// `lmbda = 1e-4` (every real call site), `bounds` wide open (a caller
    /// that does not care about the visibility gate gets it as a no-op).
    fn default() -> Self {
        Self {
            iterations: 2,
            fixedp: 1,
            lmbda: 1e-4,
            ep: 100.0,
            bounds: [
                f64::NEG_INFINITY,
                f64::NEG_INFINITY,
                f64::INFINITY,
                f64::INFINITY,
            ],
        }
    }
}

/// Errors from [`dpvo_ba`]/[`dpvo_ba_step`]. Mirrors
/// `crate::bundle::BaError`'s naming for a linear-solve failure; `ba.py`
/// itself has no error path (`torch.linalg.solve` simply raises), so this is
/// this port's own (documented, not upstream) addition — the alternative,
/// panicking on a singular system, would be worse for a library entry point.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DpvoBaError {
    /// The damped pose Schur complement was singular (numerically
    /// non-invertible). With `ep = 100.0` this should not happen on any
    /// well-posed problem; a caller hitting this should suspect degenerate
    /// input (e.g. duplicate/zero-Jacobian edges) rather than treat it as a
    /// routine retry-with-larger-damping case the way `bundle.rs`'s LM loop
    /// does — `fastba.BA` has no such retry loop upstream either.
    SingularSystem,
}

impl std::fmt::Display for DpvoBaError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            DpvoBaError::SingularSystem => {
                write!(
                    f,
                    "dpvo patch bundle adjustment: damped pose system is singular"
                )
            }
        }
    }
}

impl std::error::Error for DpvoBaError {}

/// Convert a DPVO/lietorch pose row `[tx, ty, tz, qx, qy, qz, qw]` (the
/// `ba_fixture.npz` `poses_in`/`poses_after_iter{1,2}` row layout) into
/// [`SE3`]. See the module doc's "Convention mapping" section.
pub fn se3_from_dpvo_pose(row: [f64; 7]) -> SE3 {
    let translation = Vector3::new(row[0], row[1], row[2]);
    let rotation = UnitQuaternion::from_quaternion(Quaternion::new(row[6], row[3], row[4], row[5]));
    SE3::new(rotation, translation)
}

/// Inverse of [`se3_from_dpvo_pose`]: [`SE3`] back to a DPVO-layout
/// `[tx, ty, tz, qx, qy, qz, qw]` row.
pub fn dpvo_pose_from_se3(pose: &SE3) -> [f64; 7] {
    let q = pose.rotation.quaternion();
    [
        pose.translation.x,
        pose.translation.y,
        pose.translation.z,
        q.i,
        q.j,
        q.k,
        q.w,
    ]
}

/// One edge's projective-transform outputs: the predicted (uncorrected)
/// target-frame pixel, the residual-validity flag, and the three analytic
/// Jacobians. Ports `projective_ops.py::transform`'s `jacobian=True` branch
/// (lines 71-108) for a single edge — the batched `(edges, P, P, ...)` tensor
/// shape upstream carries collapses to a single point/Jacobian per edge here
/// because (a) only the patch center pixel ever feeds `BA()`'s residual or
/// Jacobians, and (b) this module solves one edge at a time in a plain Rust
/// loop rather than a batched tensor op.
///
/// `pub(crate)`: reused verbatim by [`crate::dpvo_vi_ba`] (Milestone M5),
/// which assembles the *same* per-edge visual normal-equation contributions
/// this module's own [`dpvo_ba_step`] does (see that module's doc, "Visual
/// assembly is a deliberate, tested duplication, not a refactor" for why it
/// re-derives its own accumulation loop from these primitives instead of
/// calling into `dpvo_ba_step` directly).
pub(crate) struct EdgeGeometry {
    pub(crate) coords_center: Vector2<f64>,
    /// `(Z > 0.2)` at the transformed center pixel — `projective_ops.py:108`.
    pub(crate) valid_depth: bool,
    /// `∂coords/∂ξ_i`, `2×6`, tangent order `[ρ; ω]`.
    pub(crate) ji: SMatrix<f64, 2, 6>,
    /// `∂coords/∂ξ_j`, `2×6`.
    pub(crate) jj: SMatrix<f64, 2, 6>,
    /// `∂coords/∂d_k`, `2×1` (stored as a 2-vector).
    pub(crate) jz: Vector2<f64>,
}

/// Port of `projective_ops.py::transform(..., jacobian=True)` (lines 53-113)
/// plus `iproj`/`proj` (lines 19-50), for one edge. `pose_i`/`pose_j` are
/// `T_world_to_camera` for the edge's `i`/`j` frames; `intr_i`/`intr_j` their
/// intrinsics; `patch` the `(x, y, d)` state of the edge's patch `k`.
pub(crate) fn transform_edge(
    pose_i: &SE3,
    pose_j: &SE3,
    intr_i: &DpvoIntrinsics,
    intr_j: &DpvoIntrinsics,
    patch: &DpvoPatch,
) -> EdgeGeometry {
    // iproj (projective_ops.py:19-29): backproject the patch center to the
    // unnormalized homogeneous point (xn, yn, 1, d) in frame i's normalized
    // camera coordinates.
    let xn = (patch.x - intr_i.cx) / intr_i.fx;
    let yn = (patch.y - intr_i.cy) / intr_i.fy;
    let d = patch.inverse_depth;

    // Gij = poses[jj] * poses[ii].inv() (projective_ops.py:60).
    let g_ij = pose_j.compose(&pose_i.inverse());

    // X1 = Gij . (xn, yn, 1, d): SE3's generalized-homogeneous action, see
    // the module doc's "projective transform" section. R/t of Gij:
    let r = g_ij.rotation.to_rotation_matrix().into_inner();
    let t = g_ij.translation;
    let xyz0 = Vector3::new(xn, yn, 1.0);
    let xyz1 = r * xyz0 + t * d;
    let (x1, y1, z1) = (xyz1.x, xyz1.y, xyz1.z);
    let h1 = d; // the homogeneous weight is invariant under the action.

    // proj (projective_ops.py:32-50): perspective-divide by Z (not the
    // homogeneous weight — the ratio is invariant to their shared scale).
    let depth_inv_proj = 1.0 / z1.max(PROJECT_MIN_Z);
    let coords_center = Vector2::new(
        intr_j.fx * (depth_inv_proj * x1) + intr_j.cx,
        intr_j.fy * (depth_inv_proj * y1) + intr_j.cy,
    );

    // Residual-validity mask (projective_ops.py:108): strict Z > 0.2, not |Z|.
    let valid_depth = z1 > VALID_Z_THRESH;

    // Jacobian-only divide-by-zero guard (projective_ops.py:79-80): |Z| > 0.2,
    // a *different* condition from the validity mask above.
    let depth_inv_jac = if z1.abs() > JACOBIAN_MIN_ABS_Z {
        1.0 / z1
    } else {
        0.0
    };

    // Ja (4x6): projective_ops.py:83-88, tangent order (rho, phi).
    #[rustfmt::skip]
    let ja: SMatrix<f64, 4, 6> = SMatrix::from_row_slice(&[
        h1,  0.0, 0.0, 0.0,  z1, -y1,
        0.0,  h1, 0.0, -z1, 0.0,  x1,
        0.0, 0.0,  h1,  y1, -x1, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
    ]);

    // Jp (2x4): projective_ops.py:98-101.
    #[rustfmt::skip]
    let jp: SMatrix<f64, 2, 4> = SMatrix::from_row_slice(&[
        intr_j.fx * depth_inv_jac, 0.0, -intr_j.fx * x1 * depth_inv_jac * depth_inv_jac, 0.0,
        0.0, intr_j.fy * depth_inv_jac, -intr_j.fy * y1 * depth_inv_jac * depth_inv_jac, 0.0,
    ]);

    let jj_mat: SMatrix<f64, 2, 6> = jp * ja;
    // Ji = -Gij.adjT(Jj) = -(Jj @ Ad(Gij)) (projective_ops.py:104).
    let ji_mat: SMatrix<f64, 2, 6> = -(jj_mat * g_ij.adjoint());
    // Jz = Jp @ Gij.matrix()[:, 3:] (projective_ops.py:106).
    let g_ij_matrix = g_ij.matrix();
    let translation_column = g_ij_matrix.fixed_view::<4, 1>(0, 3);
    let jz_col = jp * translation_column;
    let jz = Vector2::new(jz_col[0], jz_col[1]);

    EdgeGeometry {
        coords_center,
        valid_depth,
        ji: ji_mat,
        jj: jj_mat,
        jz,
    }
}

/// The part of `projective_ops.py::transform`'s `Gij` action that depends
/// only on the edge's *pose pair* (`pose_i`, `pose_j`, `translation_only`),
/// not on which pixel of the patch is being reprojected: `Gij = poses[jj] *
/// poses[ii].inv()` (projective_ops.py:60), decomposed once into its
/// rotation matrix and translation vector.
///
/// # Why this exists (M4-perf, `docs/dpvo_droid_port_plan.md`)
///
/// [`reproject_patch_grid`] originally called the (now-)[`project_with_invariant`]
/// math nine times per edge — once per `3×3` grid pixel — and every one of
/// those nine calls independently recomputed `pose_j.compose(&pose_i.inverse())`
/// and the quaternion→rotation-matrix conversion, even though all nine share
/// the same `pose_i`/`pose_j`/`translation_only`. Hoisting that computation
/// here (called once per edge instead of nine times) is a pure algebraic
/// factoring — the returned `(R, t)` is bit-identical to what each of the
/// nine inlined calls used to compute — not a numerics change. This was a
/// small win in isolation (a handful of matrix ops per edge against
/// `corr_cpu`'s thousands of dot products dominating the same per-frame
/// budget), but free and correct, so it stays hoisted rather than
/// reverted after profiling showed `corr_cpu` was the real hotspot.
struct ReprojectionInvariant {
    r: nalgebra::Matrix3<f64>,
    t: Vector3<f64>,
}

fn reprojection_invariant(
    pose_i: &SE3,
    pose_j: &SE3,
    translation_only: bool,
) -> ReprojectionInvariant {
    // Optionally zero the rotation to the identity (projective_ops.py:62-63:
    // `Gij[...,3:] = [0,0,0,1]` — DPVO's 7-vector layout is
    // `[tx,ty,tz,qx,qy,qz,qw]`, so slicing `[3:]` zeroes the *quaternion*
    // slots, i.e. `tonly` keeps translation and discards rotation, despite
    // sounding like the opposite). Used by [`flow_mag`]'s `tonly=True` call.
    let mut g_ij = pose_j.compose(&pose_i.inverse());
    if translation_only {
        g_ij = SE3::new(UnitQuaternion::identity(), g_ij.translation);
    }
    ReprojectionInvariant {
        r: g_ij.rotation.to_rotation_matrix().into_inner(),
        t: g_ij.translation,
    }
}

/// Jacobian-free core of `projective_ops.py::transform` (lines 56-68: `iproj`,
/// the `SE3`/`Gij` action, `proj`), evaluated at one arbitrary pixel
/// `(x, y)` with shared inverse depth `d` given an already-computed
/// [`ReprojectionInvariant`] — i.e. exactly [`transform_edge`]'s geometry
/// computation minus the analytic Jacobians, generalized to any pixel of a
/// patch's `3×3` grid rather than only its center. Added for Milestone M4
/// (`docs/dpvo_droid_port_plan.md`): the per-frame VO loop needs this for two
/// things `dpvo_patch_ba`'s BA-only M3 scope never required — correlation-
/// lookup coordinates for the *whole* patch grid ([`reproject_patch_grid`])
/// and the keyframe motion-magnitude gate ([`flow_mag`]), neither of which
/// touches a Jacobian.
fn project_with_invariant(
    inv: &ReprojectionInvariant,
    intr_i: &DpvoIntrinsics,
    intr_j: &DpvoIntrinsics,
    x: f64,
    y: f64,
    inverse_depth: f64,
) -> Vector2<f64> {
    let xn = (x - intr_i.cx) / intr_i.fx;
    let yn = (y - intr_i.cy) / intr_i.fy;
    let d = inverse_depth;

    let xyz0 = Vector3::new(xn, yn, 1.0);
    let xyz1 = inv.r * xyz0 + inv.t * d;
    let z1 = xyz1.z;

    // proj (projective_ops.py:32-50): perspective-divide by Z.
    let depth_inv_proj = 1.0 / z1.max(PROJECT_MIN_Z);
    Vector2::new(
        intr_j.fx * (depth_inv_proj * xyz1.x) + intr_j.cx,
        intr_j.fy * (depth_inv_proj * xyz1.y) + intr_j.cy,
    )
}

/// Single-pixel convenience wrapper around [`reprojection_invariant`] +
/// [`project_with_invariant`] for call sites (just [`transform_point`]) that
/// only ever reproject one pixel per edge, where hoisting would have no
/// benefit.
#[allow(clippy::too_many_arguments)]
fn project_no_jacobian(
    pose_i: &SE3,
    pose_j: &SE3,
    intr_i: &DpvoIntrinsics,
    intr_j: &DpvoIntrinsics,
    x: f64,
    y: f64,
    inverse_depth: f64,
    translation_only: bool,
) -> Vector2<f64> {
    let inv = reprojection_invariant(pose_i, pose_j, translation_only);
    project_with_invariant(&inv, intr_i, intr_j, x, y, inverse_depth)
}

/// Reproject a patch's anchor pixel `(x, y, d)` from frame `i` into frame
/// `j`, no Jacobian, matching `projective_ops.py::transform(...,
/// jacobian=False)` for a single point. `translation_only` is `transform`'s
/// `tonly` flag (see [`project_no_jacobian`]'s doc for what it actually
/// zeroes).
pub fn transform_point(
    pose_i: &SE3,
    pose_j: &SE3,
    intr_i: &DpvoIntrinsics,
    intr_j: &DpvoIntrinsics,
    patch: &DpvoPatch,
    translation_only: bool,
) -> Vector2<f64> {
    project_no_jacobian(
        pose_i,
        pose_j,
        intr_i,
        intr_j,
        patch.x,
        patch.y,
        patch.inverse_depth,
        translation_only,
    )
}

/// Reproject every pixel of a patch's `3×3` grid (integer offsets `dx, dy ∈
/// {-1, 0, 1}` from the anchor, sharing the patch's one scalar inverse
/// depth — see the module doc's "projective transform" section on why a
/// DPVO patch's `3×3` grid shares one `(x, y, d)`-anchored depth but *not*
/// one `(x, y)`) from frame `i` into frame `j`. This is what
/// [`DPVO.reproject`]-equivalent correlation-coordinate computation needs
/// (M2's `corr_cpu` consumes a per-patch-pixel coordinate, not just a
/// center), unlike [`transform_edge`]'s BA-only center-pixel scope.
///
/// Returns a `[[Vector2<f64>; 3]; 3]` indexed `[dy+1][dx+1]` (row-major,
/// matching `corr_cpu`'s own `(py, px)` axis order in
/// `crates/vision/src/dpvo/correlation.rs`).
///
/// [`DPVO.reproject`]: https://github.com/princeton-vl/DPVO/blob/main/dpvo/dpvo.py
pub fn reproject_patch_grid(
    pose_i: &SE3,
    pose_j: &SE3,
    intr_i: &DpvoIntrinsics,
    intr_j: &DpvoIntrinsics,
    patch: &DpvoPatch,
) -> [[Vector2<f64>; 3]; 3] {
    // M4-perf (`docs/dpvo_droid_port_plan.md`): computed once and reused for
    // all nine grid pixels below instead of once per pixel — see
    // [`reprojection_invariant`]'s doc for why this is a pure hoist, not a
    // numerics change.
    let inv = reprojection_invariant(pose_i, pose_j, false);
    let mut out = [[Vector2::new(0.0, 0.0); 3]; 3];
    for (row_index, dy) in (-1..=1i32).enumerate() {
        for (col_index, dx) in (-1..=1i32).enumerate() {
            out[row_index][col_index] = project_with_invariant(
                &inv,
                intr_i,
                intr_j,
                patch.x + dx as f64,
                patch.y + dy as f64,
                patch.inverse_depth,
            );
        }
    }
    out
}

/// Port of `projective_ops.py::flow_mag` (lines 120-130), used by
/// `dpvo.py::motionmag`/`keyframe` (this crate's [`crate::dpvo_patch_graph`]
/// module) to decide whether a candidate keyframe carries enough motion to
/// keep. `beta` weights the "full 6-DoF reprojection flow" (`flow1`) against
/// the "translation-only reprojection flow" (`flow2`); `motionmag`'s own call
/// site always uses `beta = 0.5` (`dpvo.py:263`).
///
/// `coords0 = transform(poses, patches, intrinsics, ii, ii, kk)`
/// (`projective_ops.py:123`) reprojects the patch into its *own* source
/// frame — since `Gij` collapses to the identity whenever `i == j` and the
/// third `iproj` component is the constant `1` (not the depth), this
/// evaluates to exactly the anchor pixel `(x, y)` for *any* pose/intrinsics,
/// independent of the patch's depth — confirmed algebraically here (not
/// asserted blindly): `iproj` gives `(xn, yn, 1, d)`; the identity action
/// leaves it unchanged; `proj` computes `depth = 1/max(Z,0.1) = 1/max(1,0.1)
/// = 1`, so `x = fx·xn + cx = x`, `y = fy·yn + cy = y` exactly. This module
/// still calls [`transform_point`] with `pose_i == pose_j` rather than
/// hardcoding `(x, y)`, so a future reader can verify the derivation by
/// inspection rather than trust this comment.
pub fn flow_mag(
    pose_i: &SE3,
    pose_j: &SE3,
    intr_i: &DpvoIntrinsics,
    intr_j: &DpvoIntrinsics,
    patch: &DpvoPatch,
    beta: f64,
) -> f64 {
    let coords0 = transform_point(pose_i, pose_i, intr_i, intr_i, patch, false);
    let coords1 = transform_point(pose_i, pose_j, intr_i, intr_j, patch, false);
    let coords2 = transform_point(pose_i, pose_j, intr_i, intr_j, patch, true);
    let flow1 = (coords1 - coords0).norm();
    let flow2 = (coords2 - coords0).norm();
    beta * flow1 + (1.0 - beta) * flow2
}

/// Depth of a patch's anchor point after reprojection into frame `j` — `Z` in
/// `projective_ops.py::transform`'s own notation, *before* the `0.1` floor
/// `proj()` applies for the perspective divide (`project_with_invariant`'s
/// `z1`, not exposed by [`transform_point`]/[`flow_mag`] today). Added for
/// Milestone M6 (`docs/dpvo_droid_port_plan.md`): `crate::dpvo_loop_closure`'s
/// port of `patchgraph.py::edges_loop` needs the exact same validity mask
/// `projective_ops.py::transform(..., valid=True)` computes
/// (`X1[...,2] > 0.2`, `projective_ops.py:113`) to decide whether a candidate
/// loop edge's flow-magnitude sample is usable, and no existing function in
/// this module exposes the un-clamped `Z` a caller needs for that comparison.
/// Recomputes [`reprojection_invariant`] rather than threading a new output
/// parameter through [`transform_point`]/[`flow_mag`] — this is called only
/// from the `GLOBAL_OPT_FREQ`-throttled loop-candidate search (not
/// `update_step`'s per-frame hot path), so the extra ~10 flops of duplicate
/// work is immaterial (see `dpvo_loop_closure.rs`'s own module doc for the
/// call site and its cost budget).
pub fn reprojected_center_depth(
    pose_i: &SE3,
    pose_j: &SE3,
    intr_i: &DpvoIntrinsics,
    patch: &DpvoPatch,
) -> f64 {
    let inv = reprojection_invariant(pose_i, pose_j, false);
    let xn = (patch.x - intr_i.cx) / intr_i.fx;
    let yn = (patch.y - intr_i.cy) / intr_i.fy;
    let xyz0 = Vector3::new(xn, yn, 1.0);
    let xyz1 = inv.r * xyz0 + inv.t * patch.inverse_depth;
    xyz1.z
}

/// Run [`dpvo_ba_step`] `config.iterations` times, re-linearizing at the
/// updated poses/patches each time and keeping `targets`/`weights`/`edges`
/// fixed — the caller-side loop DPVO's real (CUDA) `fastba.BA(..., iterations=2)`
/// bakes in internally, but which the pure-Python reference this module ports
/// leaves to its caller (see the module doc's "Iteration count" section).
pub fn dpvo_ba(
    problem: &DpvoBaProblem,
    config: &DpvoBaConfig,
) -> Result<DpvoBaProblem, DpvoBaError> {
    let mut current = problem.clone();
    for _ in 0..config.iterations {
        current = dpvo_ba_step(&current, config)?;
    }
    Ok(current)
}

/// One Gauss-Newton iteration — the direct port of `ba.py`'s whole `BA()`
/// function (lines 86-182). See the module doc for the damping/gating/
/// convention notes this function's comments assume.
pub fn dpvo_ba_step(
    problem: &DpvoBaProblem,
    config: &DpvoBaConfig,
) -> Result<DpvoBaProblem, DpvoBaError> {
    let n_frames = problem.poses.len();
    let fixedp = config.fixedp.min(n_frames);
    let n2 = n_frames - fixedp;

    // kx, kk = torch.unique(kk, return_inverse=True, sorted=True) (ba.py:137).
    let mut used_patches: Vec<usize> = problem.edges.iter().map(|edge| edge.k).collect();
    used_patches.sort_unstable();
    used_patches.dedup();
    let m = used_patches.len();
    let local_patch_index = |k: usize| {
        used_patches
            .binary_search(&k)
            .expect("k is drawn from used_patches")
    };

    // Per-edge geometry, residual, and gated weight (ba.py:92-112).
    struct EdgeContribution {
        i_local: Option<usize>,
        j_local: Option<usize>,
        k_local: usize,
        w_ji: SMatrix<f64, 2, 6>,
        w_jj: SMatrix<f64, 2, 6>,
        w_jz: Vector2<f64>,
        ji: SMatrix<f64, 2, 6>,
        jj: SMatrix<f64, 2, 6>,
        jz: Vector2<f64>,
        r: Vector2<f64>,
    }

    let mut contributions = Vec::with_capacity(problem.edges.len());
    for (edge_index, edge) in problem.edges.iter().enumerate() {
        let geom = transform_edge(
            &problem.poses[edge.i],
            &problem.poses[edge.j],
            &problem.intrinsics[edge.i],
            &problem.intrinsics[edge.j],
            &problem.patches[edge.k],
        );

        let raw_residual = problem.targets[edge_index] - geom.coords_center;
        // v *= (r.norm(dim=-1) < 250).float() (ba.py:98), composed with the
        // Z-validity mask already carried on `geom`.
        let mut valid = geom.valid_depth && raw_residual.norm() < RESIDUAL_NORM_GATE_PX;
        // in_bounds gate on the *predicted* pixel (ba.py:100-106).
        let [x0, y0, x1, y1] = config.bounds;
        let in_bounds = geom.coords_center.x > x0
            && geom.coords_center.y > y0
            && geom.coords_center.x < x1
            && geom.coords_center.y < y1;
        valid = valid && in_bounds;

        let v = if valid { 1.0 } else { 0.0 };
        let r = raw_residual * v; // ba.py:111
        let weight = problem.weights[edge_index] * v; // ba.py:112

        // wJiT/wJjT/wJzT (ba.py:114-116): scale each Jacobian *row* (the u/v
        // reprojection channel) by weight's matching component — weight is a
        // diagonal 2x2 information matrix, not a scalar.
        let mut w_ji = geom.ji;
        w_ji.row_mut(0).scale_mut(weight.x);
        w_ji.row_mut(1).scale_mut(weight.y);
        let mut w_jj = geom.jj;
        w_jj.row_mut(0).scale_mut(weight.x);
        w_jj.row_mut(1).scale_mut(weight.y);
        let w_jz = Vector2::new(geom.jz.x * weight.x, geom.jz.y * weight.y);

        let i_local = if edge.i >= fixedp {
            Some(edge.i - fixedp)
        } else {
            None
        };
        let j_local = if edge.j >= fixedp {
            Some(edge.j - fixedp)
        } else {
            None
        };

        contributions.push(EdgeContribution {
            i_local,
            j_local,
            k_local: local_patch_index(edge.k),
            w_ji,
            w_jj,
            w_jz,
            ji: geom.ji,
            jj: geom.jj,
            jz: geom.jz,
            r,
        });
    }

    // Assemble B (n2*6 x n2*6), E (n2*6 x m), v_rhs (n2*6), C (m), w_rhs (m).
    // Pose-indexed accumulation is gated on the fixed-pose mask
    // (safe_scatter_add_mat/vec, ba.py:40-46, 140-151); the patch-indexed
    // C/w_rhs accumulation (ba.py:148, 153) is NOT gated on pose validity —
    // see the module doc's "t0/fixedp" section.
    let mut b_mat = DMatrix::<f64>::zeros(6 * n2, 6 * n2);
    let mut e_mat = DMatrix::<f64>::zeros(6 * n2, m);
    let mut v_rhs = DVector::<f64>::zeros(6 * n2);
    let mut c_diag = DVector::<f64>::zeros(m);
    let mut w_rhs = DVector::<f64>::zeros(m);

    for contribution in &contributions {
        let EdgeContribution {
            i_local,
            j_local,
            k_local,
            w_ji,
            w_jj,
            w_jz,
            ji,
            jj,
            jz,
            r,
        } = contribution;
        let k_local = *k_local;

        // Depth-channel terms: unconditional on pose validity (ba.py:148, 153).
        c_diag[k_local] += w_jz.x * jz.x + w_jz.y * jz.y;
        w_rhs[k_local] += w_jz.x * r.x + w_jz.y * r.y;

        if let Some(i) = i_local {
            let bii = w_ji.transpose() * ji;
            b_mat
                .view_mut((i * 6, i * 6), (6, 6))
                .iter_mut()
                .zip(bii.iter())
                .for_each(|(dst, src)| *dst += src);
            let vi = w_ji.transpose() * r;
            v_rhs
                .rows_mut(i * 6, 6)
                .iter_mut()
                .zip(vi.iter())
                .for_each(|(dst, src)| *dst += src);
            let eik = w_ji.transpose() * jz;
            let mut e_col = e_mat.view_mut((i * 6, k_local), (6, 1));
            e_col
                .iter_mut()
                .zip(eik.iter())
                .for_each(|(dst, src)| *dst += src);
        }
        if let Some(j) = j_local {
            let bjj = w_jj.transpose() * jj;
            b_mat
                .view_mut((j * 6, j * 6), (6, 6))
                .iter_mut()
                .zip(bjj.iter())
                .for_each(|(dst, src)| *dst += src);
            let vj = w_jj.transpose() * r;
            v_rhs
                .rows_mut(j * 6, 6)
                .iter_mut()
                .zip(vj.iter())
                .for_each(|(dst, src)| *dst += src);
            let ejk = w_jj.transpose() * jz;
            let mut e_col = e_mat.view_mut((j * 6, k_local), (6, 1));
            e_col
                .iter_mut()
                .zip(ejk.iter())
                .for_each(|(dst, src)| *dst += src);
        }
        if let (Some(i), Some(j)) = (i_local, j_local) {
            let bij = w_ji.transpose() * jj;
            b_mat
                .view_mut((i * 6, j * 6), (6, 6))
                .iter_mut()
                .zip(bij.iter())
                .for_each(|(dst, src)| *dst += src);
            let bji = w_jj.transpose() * ji;
            b_mat
                .view_mut((j * 6, i * 6), (6, 6))
                .iter_mut()
                .zip(bji.iter())
                .for_each(|(dst, src)| *dst += src);
        }
    }

    // Q = 1 / (C + lmbda) (ba.py:158). Milestone M15 ("depth-trust damping",
    // see `DpvoBaProblem::depth_damping`'s own doc): when a per-patch
    // multiplier vector is supplied, patch `k_local`'s (`used_patches[k_local]`
    // in GLOBAL patch-index terms) `lmbda` term is scaled by its own entry
    // instead of the shared scalar every prior milestone used unconditionally
    // — `problem.depth_damping.is_none()` reproduces the original expression
    // exactly (multiplier `1.0` for every patch).
    let q: DVector<f64> = DVector::from_iterator(
        m,
        used_patches.iter().enumerate().map(|(local, &global_k)| {
            let multiplier = problem.depth_damping.as_ref().map_or(1.0, |d| d[global_k]);
            1.0 / (c_diag[local] + config.lmbda * multiplier)
        }),
    );

    // dZ (and dX, unless n2 == 0) via the Schur complement (ba.py:160-173).
    let (dx, dz): (DVector<f64>, DVector<f64>) = if n2 == 0 {
        // structure_only-equivalent branch (ba.py:163-164): dZ = Q * w.
        let dz = DVector::from_iterator(m, (0..m).map(|k| q[k] * w_rhs[k]));
        (DVector::zeros(0), dz)
    } else {
        // EQ = E * Q (per-column scale, ba.py:161).
        let mut eq = e_mat.clone();
        for k in 0..m {
            let mut col = eq.column_mut(k);
            col *= q[k];
        }
        // S = B - EQ @ E^T (ba.py:167).
        let mut s = &b_mat - &eq * e_mat.transpose();
        // y = v - EQ @ w (ba.py:168).
        let y = &v_rhs - &eq * &w_rhs;

        // Damping (ba.py:169, block_solve's own A + (ep + lm*A)*eye — see
        // the module doc's "Damping" section, constant 3): per-scalar
        // diagonal only.
        for d in 0..6 * n2 {
            s[(d, d)] = s[(d, d)] * (1.0 + POSE_DIAG_LM) + config.ep;
        }

        let dx = s.lu().solve(&y).ok_or(DpvoBaError::SingularSystem)?;

        // dZ = Q * (w - E^T @ dX) (ba.py:171).
        let et_dx = e_mat.transpose() * &dx;
        let dz = DVector::from_iterator(m, (0..m).map(|k| q[k] * (w_rhs[k] - et_dx[k])));
        (dx, dz)
    };

    // Retract patches (ba.py:175-177): only the patches referenced by an
    // edge (`used_patches`) receive a `dZ`; every patch is still re-clamped
    // (disps.clamp is applied to the *whole* tensor, ba.py:176).
    let mut new_patches = problem.patches.clone();
    for (local, &global_k) in used_patches.iter().enumerate() {
        new_patches[global_k].inverse_depth += dz[local];
    }
    for patch in &mut new_patches {
        patch.inverse_depth = patch.inverse_depth.clamp(DISP_MIN, DISP_MAX);
    }

    // Retract poses (ba.py:179-180): T_f <- Exp(dX_f) * T_f, left
    // perturbation, for f in [fixedp, n_frames). Poses below fixedp are
    // untouched (they are not in the solved index space at all).
    let mut new_poses = problem.poses.clone();
    if n2 > 0 {
        for local in 0..n2 {
            let xi = nalgebra::Vector6::from_iterator((0..6).map(|c| dx[local * 6 + c]));
            let delta = SE3::exp(&xi);
            let global = fixedp + local;
            new_poses[global] = delta.compose(&problem.poses[global]);
        }
    }

    Ok(DpvoBaProblem {
        poses: new_poses,
        patches: new_patches,
        intrinsics: problem.intrinsics.clone(),
        edges: problem.edges.clone(),
        targets: problem.targets.clone(),
        weights: problem.weights.clone(),
        // Milestone M15: carried forward unchanged so `dpvo_ba`'s own
        // multi-iteration loop (`dpvo_ba_step` called `config.iterations`
        // times, re-linearizing at `current` each time) keeps damping every
        // flagged patch on every iteration, not just the first.
        depth_damping: problem.depth_damping.clone(),
    })
}

// Silence an unused-import warning if `Matrix6` ever stops being needed
// directly (kept as a documented type witness for `SE3::adjoint`'s return
// type, matched against in the module doc's adjoint section).
#[allow(dead_code)]
fn _adjoint_type_witness(m: Matrix6<f64>) -> Matrix6<f64> {
    m
}

#[cfg(test)]
mod tests {
    use super::*;

    fn intr(fx: f64, fy: f64, cx: f64, cy: f64) -> DpvoIntrinsics {
        DpvoIntrinsics { fx, fy, cx, cy }
    }

    /// A minimal two-frame, one-patch, one-edge scene where the patch
    /// reprojects (under the *current* poses/patch) exactly onto its own
    /// target pixel — i.e. `target` is computed from the same forward
    /// projection the solver itself would recompute, so the analytic
    /// residual is exactly zero before any masking. Requirement: "zero-
    /// residual fixed point (perfect data unchanged)".
    fn zero_residual_problem() -> DpvoBaProblem {
        let pose0 = SE3::identity();
        let pose1 = SE3::new(UnitQuaternion::identity(), Vector3::new(0.2, 0.0, 0.0));
        let intrinsics = intr(100.0, 100.0, 32.0, 24.0);
        let patch = DpvoPatch {
            x: 40.0,
            y: 20.0,
            inverse_depth: 0.8,
        };

        let geom = transform_edge(&pose0, &pose1, &intrinsics, &intrinsics, &patch);
        DpvoBaProblem {
            poses: vec![pose0, pose1],
            patches: vec![patch],
            intrinsics: vec![intrinsics, intrinsics],
            edges: vec![DpvoEdge { i: 0, j: 1, k: 0 }],
            targets: vec![geom.coords_center],
            weights: vec![Vector2::new(0.8, 0.8)],
            depth_damping: None,
        }
    }

    #[test]
    fn zero_residual_is_a_fixed_point() {
        let problem = zero_residual_problem();
        let config = DpvoBaConfig::default();
        let solved = dpvo_ba_step(&problem, &config).expect("solvable");

        // Pose 0 is fixed (fixedp=1) by construction, so it must be
        // bit-identical regardless of residual.
        assert_eq!(solved.poses[0], problem.poses[0]);

        // Pose 1 (free) should not move: zero residual => zero gradient
        // => dX = 0 => Exp(0) is the exact identity => compose is a
        // no-op to machine precision.
        let dt = (solved.poses[1].translation - problem.poses[1].translation).norm();
        assert!(dt < 1e-10, "pose drifted with zero residual: dt={dt}");
        let dr = (solved.poses[1].rotation.to_rotation_matrix().into_inner()
            - problem.poses[1].rotation.to_rotation_matrix().into_inner())
        .norm();
        assert!(dr < 1e-10, "rotation drifted with zero residual: dr={dr}");

        let dd = (solved.patches[0].inverse_depth - problem.patches[0].inverse_depth).abs();
        assert!(
            dd < 1e-10,
            "inverse depth drifted with zero residual: dd={dd}"
        );
    }

    /// A tiny one-free-pose, one-patch, one-edge scene with a *nonzero*
    /// residual, small enough that the Schur complement collapses to a
    /// direct `6x6` solve this test can also compute by hand (independently
    /// of `dpvo_ba_step`'s own code path) and compare against. Requirement:
    /// "a known 1-step GN reduction".
    #[test]
    fn known_one_step_gauss_newton_matches_hand_solved_6x6_system() {
        let pose0 = SE3::identity();
        let pose1 = SE3::new(UnitQuaternion::identity(), Vector3::new(0.15, 0.02, 0.0));
        let intrinsics = intr(120.0, 120.0, 32.0, 24.0);
        let patch = DpvoPatch {
            x: 36.0,
            y: 22.0,
            inverse_depth: 0.6,
        };

        let geom = transform_edge(&pose0, &pose1, &intrinsics, &intrinsics, &patch);
        // Perturb the target away from the exact reprojection so the
        // residual (and hence the update) is nonzero.
        let target = geom.coords_center + Vector2::new(0.6, -0.3);
        let weight = Vector2::new(0.9, 0.7);

        let problem = DpvoBaProblem {
            poses: vec![pose0, pose1.clone()],
            patches: vec![patch],
            intrinsics: vec![intrinsics, intrinsics],
            edges: vec![DpvoEdge { i: 0, j: 1, k: 0 }],
            targets: vec![target],
            weights: vec![weight],
            depth_damping: None,
        };
        let config = DpvoBaConfig {
            iterations: 1,
            fixedp: 1,
            lmbda: 1e-4,
            ep: 100.0,
            bounds: DpvoBaConfig::default().bounds,
        };

        // --- hand-computed expectation, independent of dpvo_ba_step ---
        let r = target - geom.coords_center;
        let mut w_jj = geom.jj;
        w_jj.row_mut(0).scale_mut(weight.x);
        w_jj.row_mut(1).scale_mut(weight.y);
        let w_jz = Vector2::new(geom.jz.x * weight.x, geom.jz.y * weight.y);
        let bjj = w_jj.transpose() * geom.jj;
        let c = w_jz.x * geom.jz.x + w_jz.y * geom.jz.y;
        let vj = w_jj.transpose() * r;
        let wj = w_jz.x * r.x + w_jz.y * r.y;
        let q = 1.0 / (c + config.lmbda);
        let e_col = w_jj.transpose() * geom.jz; // E block (6x1) for this single pose/patch pair
        let mut s = bjj - (e_col * q) * e_col.transpose();
        for d in 0..6 {
            s[(d, d)] = s[(d, d)] * (1.0 + POSE_DIAG_LM) + config.ep;
        }
        let y = vj - e_col * (q * wj);
        let expected_dx = s.lu().solve(&y).expect("hand-solved system is invertible");
        let expected_dz = q * (wj - e_col.dot(&expected_dx));

        // --- solver's actual output ---
        let solved = dpvo_ba_step(&problem, &config).expect("solvable");
        let expected_pose1 = SE3::exp(&expected_dx).compose(&pose1);

        let dt = (solved.poses[1].translation - expected_pose1.translation).norm();
        assert!(
            dt < 1e-9,
            "translation mismatch vs hand-solved system: dt={dt}"
        );
        let dr = (solved.poses[1].rotation.to_rotation_matrix().into_inner()
            - expected_pose1.rotation.to_rotation_matrix().into_inner())
        .norm();
        assert!(
            dr < 1e-9,
            "rotation mismatch vs hand-solved system: dr={dr}"
        );

        let expected_depth = (patch.inverse_depth + expected_dz).clamp(DISP_MIN, DISP_MAX);
        let dd = (solved.patches[0].inverse_depth - expected_depth).abs();
        assert!(
            dd < 1e-9,
            "inverse depth mismatch vs hand-solved system: dd={dd}"
        );
    }

    /// `fixedp` covering every pose (`fixedp = n_frames`) must leave every
    /// pose bit-identical, whatever the residual. Requirement: "fixed-pose
    /// invariance".
    #[test]
    fn all_poses_fixed_leaves_every_pose_untouched() {
        let problem = zero_residual_or_nonzero_two_frame_problem();
        let config = DpvoBaConfig {
            fixedp: problem.poses.len(),
            ..DpvoBaConfig::default()
        };
        let solved = dpvo_ba_step(&problem, &config).expect("solvable");
        for (before, after) in problem.poses.iter().zip(solved.poses.iter()) {
            assert_eq!(before, after, "a fixed pose must not move");
        }
    }

    /// Same all-fixed configuration, but checking the complementary half of
    /// the same requirement: the patch inverse depth DOES move (the n2==0
    /// / `structure_only`-equivalent branch, `ba.py:163-164`, still solves
    /// `dZ = Q * w` even though no pose is free). Requirement: "depth-only
    /// update when all poses fixed".
    #[test]
    fn depth_only_updates_when_all_poses_fixed() {
        let problem = zero_residual_or_nonzero_two_frame_problem();
        let config = DpvoBaConfig {
            fixedp: problem.poses.len(),
            ..DpvoBaConfig::default()
        };
        let solved = dpvo_ba_step(&problem, &config).expect("solvable");

        let before = problem.patches[0].inverse_depth;
        let after = solved.patches[0].inverse_depth;
        assert!(
            (after - before).abs() > 1e-6,
            "expected the patch depth to move in the all-poses-fixed branch: before={before} after={after}"
        );

        // Cross-check against the direct n2==0 formula (ba.py:163-164):
        // dZ = Q * w, with C/w computed from edges regardless of pose
        // fixing (module doc's "t0/fixedp" section).
        let pose0 = &problem.poses[0];
        let pose1 = &problem.poses[1];
        let intrinsics = problem.intrinsics[0];
        let geom = transform_edge(pose0, pose1, &intrinsics, &intrinsics, &problem.patches[0]);
        let r = problem.targets[0] - geom.coords_center;
        let weight = problem.weights[0];
        let w_jz = Vector2::new(geom.jz.x * weight.x, geom.jz.y * weight.y);
        let c = w_jz.x * geom.jz.x + w_jz.y * geom.jz.y;
        let w_rhs = w_jz.x * r.x + w_jz.y * r.y;
        let q = 1.0 / (c + config.lmbda);
        let expected_depth = (before + q * w_rhs).clamp(DISP_MIN, DISP_MAX);
        assert!(
            (after - expected_depth).abs() < 1e-9,
            "depth-only update did not match dZ = Q*w: after={after} expected={expected_depth}"
        );
    }

    /// Shared two-frame/one-patch/one-edge scene with a genuinely nonzero
    /// residual, used by the fixed-pose tests above (name says "or" because
    /// it is nonzero by construction here, but nothing in these two tests
    /// depends on that beyond "the depth moves").
    fn zero_residual_or_nonzero_two_frame_problem() -> DpvoBaProblem {
        let pose0 = SE3::identity();
        let pose1 = SE3::new(UnitQuaternion::identity(), Vector3::new(0.1, 0.0, 0.0));
        let intrinsics = intr(110.0, 110.0, 32.0, 24.0);
        let patch = DpvoPatch {
            x: 34.0,
            y: 21.0,
            inverse_depth: 0.7,
        };
        let geom = transform_edge(&pose0, &pose1, &intrinsics, &intrinsics, &patch);
        let target = geom.coords_center + Vector2::new(0.9, 0.4);
        DpvoBaProblem {
            poses: vec![pose0, pose1],
            patches: vec![patch],
            intrinsics: vec![intrinsics, intrinsics],
            edges: vec![DpvoEdge { i: 0, j: 1, k: 0 }],
            targets: vec![target],
            weights: vec![Vector2::new(0.8, 0.8)],
            depth_damping: None,
        }
    }

    #[test]
    fn dpvo_pose_round_trips_through_dpvo_layout() {
        let pose = SE3::new(
            UnitQuaternion::from_scaled_axis(Vector3::new(0.1, -0.2, 0.3)),
            Vector3::new(1.0, -2.0, 3.0),
        );
        let row = dpvo_pose_from_se3(&pose);
        let round_tripped = se3_from_dpvo_pose(row);
        assert!((round_tripped.translation - pose.translation).norm() < 1e-12);
        assert!(
            (round_tripped.rotation.to_rotation_matrix().into_inner()
                - pose.rotation.to_rotation_matrix().into_inner())
            .norm()
                < 1e-12
        );
    }

    #[test]
    fn two_iterations_reduces_residual_further_than_one() {
        // Not one of the four required hand-built tests, but a cheap sanity
        // check that the outer dpvo_ba loop (config.iterations) is actually
        // wired to call dpvo_ba_step repeatedly and re-linearize, matching
        // the module doc's "Iteration count" section.
        let problem = zero_residual_or_nonzero_two_frame_problem();
        let one = dpvo_ba(
            &problem,
            &DpvoBaConfig {
                iterations: 1,
                ..DpvoBaConfig::default()
            },
        )
        .expect("solvable");
        let two = dpvo_ba(
            &problem,
            &DpvoBaConfig {
                iterations: 2,
                ..DpvoBaConfig::default()
            },
        )
        .expect("solvable");

        let residual_after = |p: &DpvoBaProblem| -> f64 {
            let geom = transform_edge(
                &p.poses[0],
                &p.poses[1],
                &p.intrinsics[0],
                &p.intrinsics[1],
                &p.patches[0],
            );
            (p.targets[0] - geom.coords_center).norm()
        };
        let r1 = residual_after(&one);
        let r2 = residual_after(&two);
        assert!(
            r2 <= r1 + 1e-9,
            "second GN iteration should not increase the residual: r1={r1} r2={r2}"
        );
    }

    // --- Milestone M15: per-patch depth damping (docs/dpvo_droid_port_plan.md,
    // "M15 results", Option B — see `DpvoBaProblem::depth_damping`'s own doc
    // for the mechanism) ---

    /// A deliberately near-zero-parallax 2-frame/1-patch/1-edge scene — the
    /// exact regime M13's own diagnosis pins as the failure mode this
    /// mechanism targets (`docs/dpvo_droid_port_plan.md`'s "M13 results":
    /// with almost no baseline, the depth Jacobian `jz` is tiny, so the
    /// depth-channel Hessian `C[k]` is tiny too, and `q = 1/(C + lmbda)` is
    /// dominated by the bare `lmbda` FLOOR rather than real visual evidence —
    /// exactly the condition under which inflating that floor via a per-
    /// patch multiplier has a large, measurable effect). A fixture with a
    /// substantial baseline (e.g. `zero_residual_or_nonzero_two_frame_problem`,
    /// used by this module's other tests) is the WRONG regime to prove this
    /// mechanism in: there, `C[k]` already dominates `lmbda` outright, so
    /// even a 1000x multiplier changes `q` negligibly — confirmed by running
    /// exactly that fixture through this test first and observing dz_damped
    /// barely differ from dz_undamped, before switching to this near-zero-
    /// baseline construction.
    fn near_zero_parallax_problem() -> DpvoBaProblem {
        let pose0 = SE3::identity();
        // 1e-4 m translation, no rotation: almost no real depth-observing
        // baseline, but not exactly zero (avoids degenerate/singular
        // corner cases).
        let pose1 = SE3::new(UnitQuaternion::identity(), Vector3::new(1e-4, 0.0, 0.0));
        let intrinsics = intr(110.0, 110.0, 32.0, 24.0);
        let patch = DpvoPatch {
            x: 34.0,
            y: 21.0,
            inverse_depth: 0.7,
        };
        let geom = transform_edge(&pose0, &pose1, &intrinsics, &intrinsics, &patch);
        // A large-relative-to-the-tiny-Jacobian target perturbation — the
        // "BA-noise-driven residual reprojected through an almost-flat
        // depth Jacobian" M13's own Finding C describes.
        let target = geom.coords_center + Vector2::new(2.0, -1.0);
        DpvoBaProblem {
            poses: vec![pose0, pose1],
            patches: vec![patch],
            intrinsics: vec![intrinsics, intrinsics],
            edges: vec![DpvoEdge { i: 0, j: 1, k: 0 }],
            targets: vec![target],
            weights: vec![Vector2::new(0.8, 0.8)],
            depth_damping: None,
        }
    }

    #[test]
    fn depth_damping_multiplier_shrinks_that_patch_depth_update() {
        // Solved twice: once undamped (`depth_damping: None`), once with a
        // heavy per-patch multiplier on the ONLY patch present. If the
        // Schur-complement threading is correct, the damped solve's depth
        // update must be far smaller in magnitude — the direct "does M15's
        // mechanism do anything" proof, on the near-zero-parallax fixture
        // this mechanism is actually meant for (see
        // `near_zero_parallax_problem`'s own doc for why a well-conditioned
        // fixture cannot demonstrate this).
        let undamped = near_zero_parallax_problem();
        let mut damped = undamped.clone();
        damped.depth_damping = Some(vec![1000.0]);

        let config = DpvoBaConfig::default();
        let solved_undamped = dpvo_ba_step(&undamped, &config).expect("solvable");
        let solved_damped = dpvo_ba_step(&damped, &config).expect("solvable");

        let dz_undamped =
            (solved_undamped.patches[0].inverse_depth - undamped.patches[0].inverse_depth).abs();
        let dz_damped =
            (solved_damped.patches[0].inverse_depth - damped.patches[0].inverse_depth).abs();
        assert!(
            dz_undamped > 1e-6,
            "fixture should have a genuinely nonzero undamped update: dz={dz_undamped}"
        );
        assert!(
            dz_damped < dz_undamped / 10.0,
            "a 1000x lmbda multiplier should shrink the depth update by at least 10x: undamped={dz_undamped} damped={dz_damped}"
        );
    }

    #[test]
    fn depth_damping_all_ones_matches_none_exactly() {
        // `Some(vec![1.0; m])` must reproduce the pre-M15 `q = 1/(C + lmbda)`
        // expression bit-for-bit — the "off is a true no-op" contract every
        // milestone in this port relies on (see e.g. M8/M14's own
        // "byte-for-byte" language). Uses the ordinary (well-conditioned)
        // fixture — this equivalence must hold regardless of conditioning.
        let none_problem = zero_residual_or_nonzero_two_frame_problem();
        let mut ones_problem = none_problem.clone();
        ones_problem.depth_damping = Some(vec![1.0]);

        let config = DpvoBaConfig::default();
        let solved_none = dpvo_ba_step(&none_problem, &config).expect("solvable");
        let solved_ones = dpvo_ba_step(&ones_problem, &config).expect("solvable");

        assert_eq!(
            solved_none.patches[0].inverse_depth,
            solved_ones.patches[0].inverse_depth
        );
        assert_eq!(
            solved_none.poses[1].translation,
            solved_ones.poses[1].translation
        );
    }

    #[test]
    fn depth_damping_is_indexed_by_global_patch_id_not_by_used_patches_local_position() {
        // `q`'s own accumulation loop walks `used_patches` (the sorted,
        // DEDUPLICATED set of patch ids any edge actually references) and
        // must look `depth_damping` up by the GLOBAL id
        // (`used_patches[local]`), not by `local` itself — a plausible
        // off-by-index bug that a fixture where every patch is referenced
        // (local == global for every entry) cannot catch. This fixture
        // deliberately leaves global patch id 1 UNREFERENCED by any edge, so
        // `used_patches == [0, 2]` and local position 1 maps to global id 2,
        // not global id 1 — if the solver read `depth_damping[local]`
        // instead of `depth_damping[global_k]`, it would consult index 1
        // (the deliberately-unused, undamped slot) for patch 2 and this
        // test's own assertion would fail.
        //
        // Near-zero-parallax pose pair (see `near_zero_parallax_problem`'s
        // own doc for why this, not a well-conditioned baseline, is the
        // regime that actually exercises the mechanism).
        let pose0 = SE3::identity();
        let pose1 = SE3::new(UnitQuaternion::identity(), Vector3::new(1e-4, 0.0, 0.0));
        let intrinsics = intr(110.0, 110.0, 32.0, 24.0);
        let patch_a = DpvoPatch {
            x: 34.0,
            y: 21.0,
            inverse_depth: 0.7,
        }; // global id 0
        let patch_unused = DpvoPatch {
            x: 10.0,
            y: 10.0,
            inverse_depth: 0.7,
        }; // global id 1, no edge
        let patch_c = DpvoPatch {
            x: 26.0,
            y: 27.0,
            inverse_depth: 0.7,
        }; // global id 2
        let geom_a = transform_edge(&pose0, &pose1, &intrinsics, &intrinsics, &patch_a);
        let geom_c = transform_edge(&pose0, &pose1, &intrinsics, &intrinsics, &patch_c);
        let target_a = geom_a.coords_center + Vector2::new(2.0, -1.0);
        let target_c = geom_c.coords_center + Vector2::new(2.0, -1.0);

        let problem = DpvoBaProblem {
            poses: vec![pose0, pose1],
            patches: vec![patch_a, patch_unused, patch_c],
            intrinsics: vec![intrinsics, intrinsics],
            edges: vec![DpvoEdge { i: 0, j: 1, k: 0 }, DpvoEdge { i: 0, j: 1, k: 2 }],
            targets: vec![target_a, target_c],
            weights: vec![Vector2::new(0.8, 0.8), Vector2::new(0.8, 0.8)],
            // Damp global patch 2 heavily; global patch 1's entry is never
            // consulted (unreferenced by any edge) and is set to an
            // implausible sentinel to make a wrong lookup obvious if this
            // test's assertion were ever loosened.
            depth_damping: Some(vec![1.0, f64::NAN, 1000.0]),
        };
        let config = DpvoBaConfig::default();
        let solved = dpvo_ba_step(&problem, &config).expect("solvable");

        let dz_a = (solved.patches[0].inverse_depth - problem.patches[0].inverse_depth).abs();
        let dz_c = (solved.patches[2].inverse_depth - problem.patches[2].inverse_depth).abs();
        assert!(dz_a > 1e-6, "patch 0 (undamped) should move: dz_a={dz_a}");
        assert!(
            dz_a.is_finite() && dz_c.is_finite(),
            "the NaN sentinel at unreferenced global id 1 must never be read"
        );
        assert!(
            dz_c < dz_a / 10.0,
            "patch 2 (damped 1000x via its own global id) should move far less than patch 0: dz_a={dz_a} dz_c={dz_c}"
        );
    }

    // --- M4 additions: transform_point / reproject_patch_grid / flow_mag ---

    #[test]
    fn transform_point_center_matches_reproject_patch_grid_center_entry() {
        let pose_i = SE3::identity();
        let pose_j = SE3::new(
            UnitQuaternion::from_scaled_axis(Vector3::new(0.0, 0.05, 0.0)),
            Vector3::new(0.3, 0.0, 0.0),
        );
        let intrinsics = intr(120.0, 120.0, 32.0, 24.0);
        let patch = DpvoPatch {
            x: 40.0,
            y: 20.0,
            inverse_depth: 0.6,
        };

        let via_transform_point =
            transform_point(&pose_i, &pose_j, &intrinsics, &intrinsics, &patch, false);
        let grid = reproject_patch_grid(&pose_i, &pose_j, &intrinsics, &intrinsics, &patch);
        let via_grid_center = grid[1][1];
        assert!(
            (via_transform_point - via_grid_center).norm() < 1e-12,
            "center of reproject_patch_grid must exactly match transform_point: {via_transform_point:?} vs {via_grid_center:?}"
        );
    }

    #[test]
    fn reproject_patch_grid_offsets_are_distinct_for_a_tilted_view() {
        // A non-identity relative pose should generally map the 9 grid
        // offsets to 9 distinct pixels (sanity check that the grid isn't
        // silently collapsing to one repeated point).
        let pose_i = SE3::identity();
        let pose_j = SE3::new(
            UnitQuaternion::from_scaled_axis(Vector3::new(0.02, 0.03, 0.0)),
            Vector3::new(0.2, 0.05, 0.0),
        );
        let intrinsics = intr(150.0, 150.0, 32.0, 24.0);
        let patch = DpvoPatch {
            x: 40.0,
            y: 20.0,
            inverse_depth: 0.5,
        };
        let grid = reproject_patch_grid(&pose_i, &pose_j, &intrinsics, &intrinsics, &patch);
        let mut flat: Vec<Vector2<f64>> = Vec::new();
        for row in &grid {
            for &v in row {
                flat.push(v);
            }
        }
        for i in 0..flat.len() {
            for j in (i + 1)..flat.len() {
                assert!(
                    (flat[i] - flat[j]).norm() > 1e-6,
                    "grid offsets {i} and {j} coincide: {flat:?}"
                );
            }
        }
    }

    #[test]
    fn flow_mag_is_zero_for_an_identical_pose_pair() {
        // i == j (both poses/intrinsics identical) => Gij is the identity
        // for both the full and translation-only transforms => flow1 =
        // flow2 = 0 regardless of beta.
        let pose = SE3::new(
            UnitQuaternion::from_scaled_axis(Vector3::new(0.1, 0.0, 0.0)),
            Vector3::new(1.0, 2.0, 3.0),
        );
        let intrinsics = intr(100.0, 100.0, 32.0, 24.0);
        let patch = DpvoPatch {
            x: 40.0,
            y: 20.0,
            inverse_depth: 0.7,
        };
        let flow = flow_mag(&pose, &pose, &intrinsics, &intrinsics, &patch, 0.5);
        assert!(
            flow < 1e-10,
            "expected zero flow for an identical pose pair, got {flow}"
        );
    }

    #[test]
    fn flow_mag_grows_with_translation_magnitude() {
        let pose_i = SE3::identity();
        let intrinsics = intr(100.0, 100.0, 32.0, 24.0);
        let patch = DpvoPatch {
            x: 40.0,
            y: 20.0,
            inverse_depth: 0.5,
        };
        let small = SE3::new(UnitQuaternion::identity(), Vector3::new(0.05, 0.0, 0.0));
        let large = SE3::new(UnitQuaternion::identity(), Vector3::new(0.5, 0.0, 0.0));
        let flow_small = flow_mag(&pose_i, &small, &intrinsics, &intrinsics, &patch, 0.5);
        let flow_large = flow_mag(&pose_i, &large, &intrinsics, &intrinsics, &patch, 0.5);
        assert!(
            flow_large > flow_small,
            "larger translation should produce larger flow magnitude: small={flow_small} large={flow_large}"
        );
    }

    #[test]
    fn reprojected_center_depth_matches_the_i_equals_j_analytic_derivation() {
        // Same algebraic fact `flow_mag`'s own doc comment already proves for
        // i==j (any patch depth): xyz1 == (xn, yn, 1), so z1 == 1.0 exactly,
        // independent of `inverse_depth`.
        let pose = SE3::new(
            UnitQuaternion::from_scaled_axis(Vector3::new(0.1, 0.0, 0.0)),
            Vector3::new(1.0, 2.0, 3.0),
        );
        let intrinsics = intr(100.0, 100.0, 32.0, 24.0);
        let patch = DpvoPatch {
            x: 40.0,
            y: 20.0,
            inverse_depth: 0.7,
        };
        let z = reprojected_center_depth(&pose, &pose, &intrinsics, &patch);
        assert!(
            (z - 1.0).abs() < 1e-10,
            "expected z==1.0 for an i==j reprojection, got {z}"
        );
    }

    #[test]
    fn reprojected_center_depth_is_negative_when_the_point_lands_behind_camera_j() {
        // pose_i == identity, patch anchored exactly at the principal point
        // (xn=yn=0) so xyz0 == (0,0,1); pose_j rotates 180 degrees about the
        // x-axis with zero translation, so Gij == pose_j and
        // xyz1 = R_ij*(0,0,1) + t_ij*d = (0,0,-1) + 0 — behind camera j
        // regardless of the patch's inverse depth (t_ij is zero here).
        let pose_i = SE3::identity();
        let pose_j = SE3::new(
            UnitQuaternion::from_axis_angle(&Vector3::x_axis(), std::f64::consts::PI),
            Vector3::zeros(),
        );
        let intrinsics = intr(100.0, 100.0, 32.0, 24.0);
        let patch = DpvoPatch {
            x: intrinsics.cx,
            y: intrinsics.cy,
            inverse_depth: 0.5,
        };
        let z = reprojected_center_depth(&pose_i, &pose_j, &intrinsics, &patch);
        assert!(
            z < 0.2,
            "expected an invalid (behind-camera-j) depth below the 0.2 gate, got {z}"
        );
    }
}
