[package]
name = "visloc-fusion"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description.workspace = true
readme.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
nalgebra = { workspace = true }
visloc-core = { path = "../../crates/core", version = "0.1.0" }
visloc-localization = { path = "../localization", version = "0.1.0" }
