// GENERATED by scripts/gen_match_wgsl.py -- edit that script, not this file.
//
// u8 variant: descriptors quantised COLMAP-style (round(512 x), clamped to
// 255) and packed four per u32. Dot products are exact integer sums
// (`dot4U8Packed`), so the k order no longer matters; scores convert to f32
// exactly (|score| < 2^24) and the top-2 logic is the f32 kernel's.
// Forward only: exact dot products make the swapped entry's forward top-2
// the reverse top-2 bit for bit, and with the cheap integer GEMM two
// forward passes beat the fused reverse epilogue (the reverse fields of
// `Entry` are ignored).
//
// Batched brute-force top-2 nearest neighbours over a device-resident
// descriptor bank (the GPU half of visloc-vision's `BruteForceMatcher`).
//
// Each entry names a query block and a train block of the bank; for every
// query row it finds the two smallest scores ||t||^2 - 2 q.t (= ||q - t||^2
// - ||q||^2, the CPU matcher's ranking) and the best train index. Ties go
// to the lower index, like the CPU's strict `<` scan. The host turns
// scores into distances, applies the ratio test and cross-checks with the
// swapped entry.
//
// One workgroup = 128 query rows x all train rows of one entry, in 128-row
// train tiles; a classic shared-memory GEMM with 16-wide k chunks (the k
// loop unrolled), each thread holding an 8 x 8 register tile (rows 4 ty + i
// and 64 + 4 ty + i, cols 4 tx + j and 64 + 4 tx + j) so every operand read
// out of shared memory is one vec4. Every dot product still sums
// k = 0..dim in order.
//
// Each thread offers its candidates to its own running top-2 in increasing
// index order, so there the index tie-break can never fire and `insert_inc`
// skips it; the folds across threads use the full `insert`.
//
// Cross-check needs the reverse top-2 as well (per train column over all
// query rows, score ||q||^2 - 2 q.t). The same dot tile gives it: each
// workgroup writes a per-column partial top-2 over its 128 rows to
// `rev_part`, and `rev_reduce` folds the row blocks. The dot products are
// bit-identical to computing the swapped entry, so the result is too.

struct MatchParams {
    // vec4<u32>s per descriptor row (dim / 16); dim is a multiple of 64.
    dim4: u32,
    num_entries: u32,
    pad0: u32,
    pad1: u32,
};

struct Entry {
    q_off: u32,
    nq: u32,
    t_off: u32,
    nt: u32,
    out_off: u32,
    // Reverse top-2: partials at rev_part[rev_part_off + block * nt + col],
    // results at out[rev_out_off + col]. rev_out_off == NONE: forward only.
    rev_part_off: u32,
    rev_out_off: u32,
    pad0: u32,
};

@group(0) @binding(0) var<uniform> p: MatchParams;
@group(0) @binding(1) var<storage, read> desc: array<vec4<u32>>;
@group(0) @binding(2) var<storage, read> norms: array<f32>;
@group(0) @binding(3) var<storage, read> entries: array<Entry>;
// Per query row: best index, best score, second score, second index.
@group(0) @binding(4) var<storage, read_write> out: array<vec4<u32>>;

const BIG: f32 = 3.0e38;
const NONE: u32 = 0xFFFFFFFFu;

// k-major tiles, four consecutive rows per vec4: qs[k * 32 + row / 4][row % 4].
// After the GEMM they double as score scratch for the top-2 folds.
var<workgroup> qs: array<vec4<u32>, 512>;
var<workgroup> ts: array<vec4<u32>, 512>;
var<workgroup> red_i1: array<u32, 2048>;
var<workgroup> red_i2: array<u32, 2048>;

struct Top2 {
    s1: f32,
    i1: u32,
    s2: f32,
    i2: u32,
};

fn before(sa: f32, ia: u32, sb: f32, ib: u32) -> bool {
    return sa < sb || (sa == sb && ia < ib);
}

// Branch-free: the same result as "new best, else new second".
fn insert(t: Top2, s: f32, i: u32) -> Top2 {
    let b1 = before(s, i, t.s1, t.i1);
    let b2 = before(s, i, t.s2, t.i2);
    return Top2(
        select(t.s1, s, b1),
        select(t.i1, i, b1),
        select(select(t.s2, s, b2), t.s1, b1),
        select(select(t.i2, i, b2), t.i1, b1),
    );
}

// `insert` for an index above every index already inserted: an equal score
// then never wins, so plain `<` gives the same scores and best index. The
// second index is dropped (NONE): it only breaks ties between equal second
// scores, which leaves the second score itself unchanged.
fn insert_inc(t: Top2, s: f32, i: u32) -> Top2 {
    let b1 = s < t.s1;
    let b2 = s < t.s2;
    return Top2(
        select(t.s1, s, b1),
        select(t.i1, i, b1),
        select(select(t.s2, s, b2), t.s1, b1),
        NONE,
    );
}

// Fold shared-memory partial `slot` (scores in qs/ts, indices in red_i*).
fn fold(c: Top2, slot: u32) -> Top2 {
    let r = insert(c, bitcast<f32>(qs[slot / 4u][slot % 4u]), red_i1[slot]);
    return insert(r, bitcast<f32>(ts[slot / 4u][slot % 4u]), red_i2[slot]);
}

fn store(slot: u32, c: Top2) {
    qs[slot / 4u][slot % 4u] = bitcast<u32>(c.s1);
    ts[slot / 4u][slot % 4u] = bitcast<u32>(c.s2);
    red_i1[slot] = c.i1;
    red_i2[slot] = c.i2;
}

// One vec4 of a 128-row x 16-k tile (512 vec4, two per thread): fetch it
// from the bank, then put it into the k-major shared tile.
fn fetch(row_off: u32, nrows: u32, row0: u32, kc: u32, t: u32, s: u32) -> vec4<u32> {
    let idx = t + 256u * s;
    let row = idx / 4u;
    let v = idx % 4u;
    if (row0 + row < nrows) {
        return desc[(row_off + row0 + row) * p.dim4 + kc * 4u + v];
    }
    return vec4<u32>(0u);
}

fn put(dst_is_q: bool, t: u32, s: u32, val: vec4<u32>) {
    let idx = t + 256u * s;
    let row = idx / 4u;
    let v = idx % 4u;
    let base = v * 4u * 32u + row / 4u;
    let c = row % 4u;
    if (dst_is_q) {
        qs[base][c] = val.x;
        qs[base + 32u][c] = val.y;
        qs[base + 64u][c] = val.z;
        qs[base + 96u][c] = val.w;
    } else {
        ts[base][c] = val.x;
        ts[base + 32u][c] = val.y;
        ts[base + 64u][c] = val.z;
        ts[base + 96u][c] = val.w;
    }
}

@compute @workgroup_size(256)
fn top2(@builtin(workgroup_id) wid: vec3<u32>, @builtin(local_invocation_id) lid: vec3<u32>) {
    let e = entries[wid.y];
    let row0 = wid.x * 128u;
    if (row0 >= e.nq) {
        return;
    }
    let t = lid.x;
    let tx = t % 16u;
    let ty = t / 16u;
    let nchunks = p.dim4 / 4u;
    var qn0 = BIG;
    if (row0 + 4u * ty + 0u < e.nq) {
        qn0 = norms[e.q_off + row0 + 4u * ty + 0u];
    }
    var r0 = Top2(BIG, NONE, BIG, NONE);
    var qn1 = BIG;
    if (row0 + 4u * ty + 1u < e.nq) {
        qn1 = norms[e.q_off + row0 + 4u * ty + 1u];
    }
    var r1 = Top2(BIG, NONE, BIG, NONE);
    var qn2 = BIG;
    if (row0 + 4u * ty + 2u < e.nq) {
        qn2 = norms[e.q_off + row0 + 4u * ty + 2u];
    }
    var r2 = Top2(BIG, NONE, BIG, NONE);
    var qn3 = BIG;
    if (row0 + 4u * ty + 3u < e.nq) {
        qn3 = norms[e.q_off + row0 + 4u * ty + 3u];
    }
    var r3 = Top2(BIG, NONE, BIG, NONE);
    var qn4 = BIG;
    if (row0 + 64u + 4u * ty + 0u < e.nq) {
        qn4 = norms[e.q_off + row0 + 64u + 4u * ty + 0u];
    }
    var r4 = Top2(BIG, NONE, BIG, NONE);
    var qn5 = BIG;
    if (row0 + 64u + 4u * ty + 1u < e.nq) {
        qn5 = norms[e.q_off + row0 + 64u + 4u * ty + 1u];
    }
    var r5 = Top2(BIG, NONE, BIG, NONE);
    var qn6 = BIG;
    if (row0 + 64u + 4u * ty + 2u < e.nq) {
        qn6 = norms[e.q_off + row0 + 64u + 4u * ty + 2u];
    }
    var r6 = Top2(BIG, NONE, BIG, NONE);
    var qn7 = BIG;
    if (row0 + 64u + 4u * ty + 3u < e.nq) {
        qn7 = norms[e.q_off + row0 + 64u + 4u * ty + 3u];
    }
    var r7 = Top2(BIG, NONE, BIG, NONE);

    for (var col0 = 0u; col0 < e.nt; col0 = col0 + 128u) {
        var acc0l = vec4<u32>(0u);
        var acc0h = vec4<u32>(0u);
        var acc1l = vec4<u32>(0u);
        var acc1h = vec4<u32>(0u);
        var acc2l = vec4<u32>(0u);
        var acc2h = vec4<u32>(0u);
        var acc3l = vec4<u32>(0u);
        var acc3h = vec4<u32>(0u);
        var acc4l = vec4<u32>(0u);
        var acc4h = vec4<u32>(0u);
        var acc5l = vec4<u32>(0u);
        var acc5h = vec4<u32>(0u);
        var acc6l = vec4<u32>(0u);
        var acc6h = vec4<u32>(0u);
        var acc7l = vec4<u32>(0u);
        var acc7h = vec4<u32>(0u);
        for (var kc = 0u; kc < nchunks; kc = kc + 1u) {
            put(true, t, 0u, fetch(e.q_off, e.nq, row0, kc, t, 0u));
            put(false, t, 0u, fetch(e.t_off, e.nt, col0, kc, t, 0u));
            put(true, t, 1u, fetch(e.q_off, e.nq, row0, kc, t, 1u));
            put(false, t, 1u, fetch(e.t_off, e.nt, col0, kc, t, 1u));
            workgroupBarrier();
            {
                let al = qs[0u + ty];
                let ah = qs[16u + ty];
                let bl = ts[0u + tx];
                let bh = ts[16u + tx];
                acc0l = acc0l + vec4<u32>(dot4U8Packed(al.x, bl.x), dot4U8Packed(al.x, bl.y), dot4U8Packed(al.x, bl.z), dot4U8Packed(al.x, bl.w));
                acc0h = acc0h + vec4<u32>(dot4U8Packed(al.x, bh.x), dot4U8Packed(al.x, bh.y), dot4U8Packed(al.x, bh.z), dot4U8Packed(al.x, bh.w));
                acc1l = acc1l + vec4<u32>(dot4U8Packed(al.y, bl.x), dot4U8Packed(al.y, bl.y), dot4U8Packed(al.y, bl.z), dot4U8Packed(al.y, bl.w));
                acc1h = acc1h + vec4<u32>(dot4U8Packed(al.y, bh.x), dot4U8Packed(al.y, bh.y), dot4U8Packed(al.y, bh.z), dot4U8Packed(al.y, bh.w));
                acc2l = acc2l + vec4<u32>(dot4U8Packed(al.z, bl.x), dot4U8Packed(al.z, bl.y), dot4U8Packed(al.z, bl.z), dot4U8Packed(al.z, bl.w));
                acc2h = acc2h + vec4<u32>(dot4U8Packed(al.z, bh.x), dot4U8Packed(al.z, bh.y), dot4U8Packed(al.z, bh.z), dot4U8Packed(al.z, bh.w));
                acc3l = acc3l + vec4<u32>(dot4U8Packed(al.w, bl.x), dot4U8Packed(al.w, bl.y), dot4U8Packed(al.w, bl.z), dot4U8Packed(al.w, bl.w));
                acc3h = acc3h + vec4<u32>(dot4U8Packed(al.w, bh.x), dot4U8Packed(al.w, bh.y), dot4U8Packed(al.w, bh.z), dot4U8Packed(al.w, bh.w));
                acc4l = acc4l + vec4<u32>(dot4U8Packed(ah.x, bl.x), dot4U8Packed(ah.x, bl.y), dot4U8Packed(ah.x, bl.z), dot4U8Packed(ah.x, bl.w));
                acc4h = acc4h + vec4<u32>(dot4U8Packed(ah.x, bh.x), dot4U8Packed(ah.x, bh.y), dot4U8Packed(ah.x, bh.z), dot4U8Packed(ah.x, bh.w));
                acc5l = acc5l + vec4<u32>(dot4U8Packed(ah.y, bl.x), dot4U8Packed(ah.y, bl.y), dot4U8Packed(ah.y, bl.z), dot4U8Packed(ah.y, bl.w));
                acc5h = acc5h + vec4<u32>(dot4U8Packed(ah.y, bh.x), dot4U8Packed(ah.y, bh.y), dot4U8Packed(ah.y, bh.z), dot4U8Packed(ah.y, bh.w));
                acc6l = acc6l + vec4<u32>(dot4U8Packed(ah.z, bl.x), dot4U8Packed(ah.z, bl.y), dot4U8Packed(ah.z, bl.z), dot4U8Packed(ah.z, bl.w));
                acc6h = acc6h + vec4<u32>(dot4U8Packed(ah.z, bh.x), dot4U8Packed(ah.z, bh.y), dot4U8Packed(ah.z, bh.z), dot4U8Packed(ah.z, bh.w));
                acc7l = acc7l + vec4<u32>(dot4U8Packed(ah.w, bl.x), dot4U8Packed(ah.w, bl.y), dot4U8Packed(ah.w, bl.z), dot4U8Packed(ah.w, bl.w));
                acc7h = acc7h + vec4<u32>(dot4U8Packed(ah.w, bh.x), dot4U8Packed(ah.w, bh.y), dot4U8Packed(ah.w, bh.z), dot4U8Packed(ah.w, bh.w));
            }
            {
                let al = qs[32u + ty];
                let ah = qs[48u + ty];
                let bl = ts[32u + tx];
                let bh = ts[48u + tx];
                acc0l = acc0l + vec4<u32>(dot4U8Packed(al.x, bl.x), dot4U8Packed(al.x, bl.y), dot4U8Packed(al.x, bl.z), dot4U8Packed(al.x, bl.w));
                acc0h = acc0h + vec4<u32>(dot4U8Packed(al.x, bh.x), dot4U8Packed(al.x, bh.y), dot4U8Packed(al.x, bh.z), dot4U8Packed(al.x, bh.w));
                acc1l = acc1l + vec4<u32>(dot4U8Packed(al.y, bl.x), dot4U8Packed(al.y, bl.y), dot4U8Packed(al.y, bl.z), dot4U8Packed(al.y, bl.w));
                acc1h = acc1h + vec4<u32>(dot4U8Packed(al.y, bh.x), dot4U8Packed(al.y, bh.y), dot4U8Packed(al.y, bh.z), dot4U8Packed(al.y, bh.w));
                acc2l = acc2l + vec4<u32>(dot4U8Packed(al.z, bl.x), dot4U8Packed(al.z, bl.y), dot4U8Packed(al.z, bl.z), dot4U8Packed(al.z, bl.w));
                acc2h = acc2h + vec4<u32>(dot4U8Packed(al.z, bh.x), dot4U8Packed(al.z, bh.y), dot4U8Packed(al.z, bh.z), dot4U8Packed(al.z, bh.w));
                acc3l = acc3l + vec4<u32>(dot4U8Packed(al.w, bl.x), dot4U8Packed(al.w, bl.y), dot4U8Packed(al.w, bl.z), dot4U8Packed(al.w, bl.w));
                acc3h = acc3h + vec4<u32>(dot4U8Packed(al.w, bh.x), dot4U8Packed(al.w, bh.y), dot4U8Packed(al.w, bh.z), dot4U8Packed(al.w, bh.w));
                acc4l = acc4l + vec4<u32>(dot4U8Packed(ah.x, bl.x), dot4U8Packed(ah.x, bl.y), dot4U8Packed(ah.x, bl.z), dot4U8Packed(ah.x, bl.w));
                acc4h = acc4h + vec4<u32>(dot4U8Packed(ah.x, bh.x), dot4U8Packed(ah.x, bh.y), dot4U8Packed(ah.x, bh.z), dot4U8Packed(ah.x, bh.w));
                acc5l = acc5l + vec4<u32>(dot4U8Packed(ah.y, bl.x), dot4U8Packed(ah.y, bl.y), dot4U8Packed(ah.y, bl.z), dot4U8Packed(ah.y, bl.w));
                acc5h = acc5h + vec4<u32>(dot4U8Packed(ah.y, bh.x), dot4U8Packed(ah.y, bh.y), dot4U8Packed(ah.y, bh.z), dot4U8Packed(ah.y, bh.w));
                acc6l = acc6l + vec4<u32>(dot4U8Packed(ah.z, bl.x), dot4U8Packed(ah.z, bl.y), dot4U8Packed(ah.z, bl.z), dot4U8Packed(ah.z, bl.w));
                acc6h = acc6h + vec4<u32>(dot4U8Packed(ah.z, bh.x), dot4U8Packed(ah.z, bh.y), dot4U8Packed(ah.z, bh.z), dot4U8Packed(ah.z, bh.w));
                acc7l = acc7l + vec4<u32>(dot4U8Packed(ah.w, bl.x), dot4U8Packed(ah.w, bl.y), dot4U8Packed(ah.w, bl.z), dot4U8Packed(ah.w, bl.w));
                acc7h = acc7h + vec4<u32>(dot4U8Packed(ah.w, bh.x), dot4U8Packed(ah.w, bh.y), dot4U8Packed(ah.w, bh.z), dot4U8Packed(ah.w, bh.w));
            }
            {
                let al = qs[64u + ty];
                let ah = qs[80u + ty];
                let bl = ts[64u + tx];
                let bh = ts[80u + tx];
                acc0l = acc0l + vec4<u32>(dot4U8Packed(al.x, bl.x), dot4U8Packed(al.x, bl.y), dot4U8Packed(al.x, bl.z), dot4U8Packed(al.x, bl.w));
                acc0h = acc0h + vec4<u32>(dot4U8Packed(al.x, bh.x), dot4U8Packed(al.x, bh.y), dot4U8Packed(al.x, bh.z), dot4U8Packed(al.x, bh.w));
                acc1l = acc1l + vec4<u32>(dot4U8Packed(al.y, bl.x), dot4U8Packed(al.y, bl.y), dot4U8Packed(al.y, bl.z), dot4U8Packed(al.y, bl.w));
                acc1h = acc1h + vec4<u32>(dot4U8Packed(al.y, bh.x), dot4U8Packed(al.y, bh.y), dot4U8Packed(al.y, bh.z), dot4U8Packed(al.y, bh.w));
                acc2l = acc2l + vec4<u32>(dot4U8Packed(al.z, bl.x), dot4U8Packed(al.z, bl.y), dot4U8Packed(al.z, bl.z), dot4U8Packed(al.z, bl.w));
                acc2h = acc2h + vec4<u32>(dot4U8Packed(al.z, bh.x), dot4U8Packed(al.z, bh.y), dot4U8Packed(al.z, bh.z), dot4U8Packed(al.z, bh.w));
                acc3l = acc3l + vec4<u32>(dot4U8Packed(al.w, bl.x), dot4U8Packed(al.w, bl.y), dot4U8Packed(al.w, bl.z), dot4U8Packed(al.w, bl.w));
                acc3h = acc3h + vec4<u32>(dot4U8Packed(al.w, bh.x), dot4U8Packed(al.w, bh.y), dot4U8Packed(al.w, bh.z), dot4U8Packed(al.w, bh.w));
                acc4l = acc4l + vec4<u32>(dot4U8Packed(ah.x, bl.x), dot4U8Packed(ah.x, bl.y), dot4U8Packed(ah.x, bl.z), dot4U8Packed(ah.x, bl.w));
                acc4h = acc4h + vec4<u32>(dot4U8Packed(ah.x, bh.x), dot4U8Packed(ah.x, bh.y), dot4U8Packed(ah.x, bh.z), dot4U8Packed(ah.x, bh.w));
                acc5l = acc5l + vec4<u32>(dot4U8Packed(ah.y, bl.x), dot4U8Packed(ah.y, bl.y), dot4U8Packed(ah.y, bl.z), dot4U8Packed(ah.y, bl.w));
                acc5h = acc5h + vec4<u32>(dot4U8Packed(ah.y, bh.x), dot4U8Packed(ah.y, bh.y), dot4U8Packed(ah.y, bh.z), dot4U8Packed(ah.y, bh.w));
                acc6l = acc6l + vec4<u32>(dot4U8Packed(ah.z, bl.x), dot4U8Packed(ah.z, bl.y), dot4U8Packed(ah.z, bl.z), dot4U8Packed(ah.z, bl.w));
                acc6h = acc6h + vec4<u32>(dot4U8Packed(ah.z, bh.x), dot4U8Packed(ah.z, bh.y), dot4U8Packed(ah.z, bh.z), dot4U8Packed(ah.z, bh.w));
                acc7l = acc7l + vec4<u32>(dot4U8Packed(ah.w, bl.x), dot4U8Packed(ah.w, bl.y), dot4U8Packed(ah.w, bl.z), dot4U8Packed(ah.w, bl.w));
                acc7h = acc7h + vec4<u32>(dot4U8Packed(ah.w, bh.x), dot4U8Packed(ah.w, bh.y), dot4U8Packed(ah.w, bh.z), dot4U8Packed(ah.w, bh.w));
            }
            {
                let al = qs[96u + ty];
                let ah = qs[112u + ty];
                let bl = ts[96u + tx];
                let bh = ts[112u + tx];
                acc0l = acc0l + vec4<u32>(dot4U8Packed(al.x, bl.x), dot4U8Packed(al.x, bl.y), dot4U8Packed(al.x, bl.z), dot4U8Packed(al.x, bl.w));
                acc0h = acc0h + vec4<u32>(dot4U8Packed(al.x, bh.x), dot4U8Packed(al.x, bh.y), dot4U8Packed(al.x, bh.z), dot4U8Packed(al.x, bh.w));
                acc1l = acc1l + vec4<u32>(dot4U8Packed(al.y, bl.x), dot4U8Packed(al.y, bl.y), dot4U8Packed(al.y, bl.z), dot4U8Packed(al.y, bl.w));
                acc1h = acc1h + vec4<u32>(dot4U8Packed(al.y, bh.x), dot4U8Packed(al.y, bh.y), dot4U8Packed(al.y, bh.z), dot4U8Packed(al.y, bh.w));
                acc2l = acc2l + vec4<u32>(dot4U8Packed(al.z, bl.x), dot4U8Packed(al.z, bl.y), dot4U8Packed(al.z, bl.z), dot4U8Packed(al.z, bl.w));
                acc2h = acc2h + vec4<u32>(dot4U8Packed(al.z, bh.x), dot4U8Packed(al.z, bh.y), dot4U8Packed(al.z, bh.z), dot4U8Packed(al.z, bh.w));
                acc3l = acc3l + vec4<u32>(dot4U8Packed(al.w, bl.x), dot4U8Packed(al.w, bl.y), dot4U8Packed(al.w, bl.z), dot4U8Packed(al.w, bl.w));
                acc3h = acc3h + vec4<u32>(dot4U8Packed(al.w, bh.x), dot4U8Packed(al.w, bh.y), dot4U8Packed(al.w, bh.z), dot4U8Packed(al.w, bh.w));
                acc4l = acc4l + vec4<u32>(dot4U8Packed(ah.x, bl.x), dot4U8Packed(ah.x, bl.y), dot4U8Packed(ah.x, bl.z), dot4U8Packed(ah.x, bl.w));
                acc4h = acc4h + vec4<u32>(dot4U8Packed(ah.x, bh.x), dot4U8Packed(ah.x, bh.y), dot4U8Packed(ah.x, bh.z), dot4U8Packed(ah.x, bh.w));
                acc5l = acc5l + vec4<u32>(dot4U8Packed(ah.y, bl.x), dot4U8Packed(ah.y, bl.y), dot4U8Packed(ah.y, bl.z), dot4U8Packed(ah.y, bl.w));
                acc5h = acc5h + vec4<u32>(dot4U8Packed(ah.y, bh.x), dot4U8Packed(ah.y, bh.y), dot4U8Packed(ah.y, bh.z), dot4U8Packed(ah.y, bh.w));
                acc6l = acc6l + vec4<u32>(dot4U8Packed(ah.z, bl.x), dot4U8Packed(ah.z, bl.y), dot4U8Packed(ah.z, bl.z), dot4U8Packed(ah.z, bl.w));
                acc6h = acc6h + vec4<u32>(dot4U8Packed(ah.z, bh.x), dot4U8Packed(ah.z, bh.y), dot4U8Packed(ah.z, bh.z), dot4U8Packed(ah.z, bh.w));
                acc7l = acc7l + vec4<u32>(dot4U8Packed(ah.w, bl.x), dot4U8Packed(ah.w, bl.y), dot4U8Packed(ah.w, bl.z), dot4U8Packed(ah.w, bl.w));
                acc7h = acc7h + vec4<u32>(dot4U8Packed(ah.w, bh.x), dot4U8Packed(ah.w, bh.y), dot4U8Packed(ah.w, bh.z), dot4U8Packed(ah.w, bh.w));
            }
            {
                let al = qs[128u + ty];
                let ah = qs[144u + ty];
                let bl = ts[128u + tx];
                let bh = ts[144u + tx];
                acc0l = acc0l + vec4<u32>(dot4U8Packed(al.x, bl.x), dot4U8Packed(al.x, bl.y), dot4U8Packed(al.x, bl.z), dot4U8Packed(al.x, bl.w));
                acc0h = acc0h + vec4<u32>(dot4U8Packed(al.x, bh.x), dot4U8Packed(al.x, bh.y), dot4U8Packed(al.x, bh.z), dot4U8Packed(al.x, bh.w));
                acc1l = acc1l + vec4<u32>(dot4U8Packed(al.y, bl.x), dot4U8Packed(al.y, bl.y), dot4U8Packed(al.y, bl.z), dot4U8Packed(al.y, bl.w));
                acc1h = acc1h + vec4<u32>(dot4U8Packed(al.y, bh.x), dot4U8Packed(al.y, bh.y), dot4U8Packed(al.y, bh.z), dot4U8Packed(al.y, bh.w));
                acc2l = acc2l + vec4<u32>(dot4U8Packed(al.z, bl.x), dot4U8Packed(al.z, bl.y), dot4U8Packed(al.z, bl.z), dot4U8Packed(al.z, bl.w));
                acc2h = acc2h + vec4<u32>(dot4U8Packed(al.z, bh.x), dot4U8Packed(al.z, bh.y), dot4U8Packed(al.z, bh.z), dot4U8Packed(al.z, bh.w));
                acc3l = acc3l + vec4<u32>(dot4U8Packed(al.w, bl.x), dot4U8Packed(al.w, bl.y), dot4U8Packed(al.w, bl.z), dot4U8Packed(al.w, bl.w));
                acc3h = acc3h + vec4<u32>(dot4U8Packed(al.w, bh.x), dot4U8Packed(al.w, bh.y), dot4U8Packed(al.w, bh.z), dot4U8Packed(al.w, bh.w));
                acc4l = acc4l + vec4<u32>(dot4U8Packed(ah.x, bl.x), dot4U8Packed(ah.x, bl.y), dot4U8Packed(ah.x, bl.z), dot4U8Packed(ah.x, bl.w));
                acc4h = acc4h + vec4<u32>(dot4U8Packed(ah.x, bh.x), dot4U8Packed(ah.x, bh.y), dot4U8Packed(ah.x, bh.z), dot4U8Packed(ah.x, bh.w));
                acc5l = acc5l + vec4<u32>(dot4U8Packed(ah.y, bl.x), dot4U8Packed(ah.y, bl.y), dot4U8Packed(ah.y, bl.z), dot4U8Packed(ah.y, bl.w));
                acc5h = acc5h + vec4<u32>(dot4U8Packed(ah.y, bh.x), dot4U8Packed(ah.y, bh.y), dot4U8Packed(ah.y, bh.z), dot4U8Packed(ah.y, bh.w));
                acc6l = acc6l + vec4<u32>(dot4U8Packed(ah.z, bl.x), dot4U8Packed(ah.z, bl.y), dot4U8Packed(ah.z, bl.z), dot4U8Packed(ah.z, bl.w));
                acc6h = acc6h + vec4<u32>(dot4U8Packed(ah.z, bh.x), dot4U8Packed(ah.z, bh.y), dot4U8Packed(ah.z, bh.z), dot4U8Packed(ah.z, bh.w));
                acc7l = acc7l + vec4<u32>(dot4U8Packed(ah.w, bl.x), dot4U8Packed(ah.w, bl.y), dot4U8Packed(ah.w, bl.z), dot4U8Packed(ah.w, bl.w));
                acc7h = acc7h + vec4<u32>(dot4U8Packed(ah.w, bh.x), dot4U8Packed(ah.w, bh.y), dot4U8Packed(ah.w, bh.z), dot4U8Packed(ah.w, bh.w));
            }
            {
                let al = qs[160u + ty];
                let ah = qs[176u + ty];
                let bl = ts[160u + tx];
                let bh = ts[176u + tx];
                acc0l = acc0l + vec4<u32>(dot4U8Packed(al.x, bl.x), dot4U8Packed(al.x, bl.y), dot4U8Packed(al.x, bl.z), dot4U8Packed(al.x, bl.w));
                acc0h = acc0h + vec4<u32>(dot4U8Packed(al.x, bh.x), dot4U8Packed(al.x, bh.y), dot4U8Packed(al.x, bh.z), dot4U8Packed(al.x, bh.w));
                acc1l = acc1l + vec4<u32>(dot4U8Packed(al.y, bl.x), dot4U8Packed(al.y, bl.y), dot4U8Packed(al.y, bl.z), dot4U8Packed(al.y, bl.w));
                acc1h = acc1h + vec4<u32>(dot4U8Packed(al.y, bh.x), dot4U8Packed(al.y, bh.y), dot4U8Packed(al.y, bh.z), dot4U8Packed(al.y, bh.w));
                acc2l = acc2l + vec4<u32>(dot4U8Packed(al.z, bl.x), dot4U8Packed(al.z, bl.y), dot4U8Packed(al.z, bl.z), dot4U8Packed(al.z, bl.w));
                acc2h = acc2h + vec4<u32>(dot4U8Packed(al.z, bh.x), dot4U8Packed(al.z, bh.y), dot4U8Packed(al.z, bh.z), dot4U8Packed(al.z, bh.w));
                acc3l = acc3l + vec4<u32>(dot4U8Packed(al.w, bl.x), dot4U8Packed(al.w, bl.y), dot4U8Packed(al.w, bl.z), dot4U8Packed(al.w, bl.w));
                acc3h = acc3h + vec4<u32>(dot4U8Packed(al.w, bh.x), dot4U8Packed(al.w, bh.y), dot4U8Packed(al.w, bh.z), dot4U8Packed(al.w, bh.w));
                acc4l = acc4l + vec4<u32>(dot4U8Packed(ah.x, bl.x), dot4U8Packed(ah.x, bl.y), dot4U8Packed(ah.x, bl.z), dot4U8Packed(ah.x, bl.w));
                acc4h = acc4h + vec4<u32>(dot4U8Packed(ah.x, bh.x), dot4U8Packed(ah.x, bh.y), dot4U8Packed(ah.x, bh.z), dot4U8Packed(ah.x, bh.w));
                acc5l = acc5l + vec4<u32>(dot4U8Packed(ah.y, bl.x), dot4U8Packed(ah.y, bl.y), dot4U8Packed(ah.y, bl.z), dot4U8Packed(ah.y, bl.w));
                acc5h = acc5h + vec4<u32>(dot4U8Packed(ah.y, bh.x), dot4U8Packed(ah.y, bh.y), dot4U8Packed(ah.y, bh.z), dot4U8Packed(ah.y, bh.w));
                acc6l = acc6l + vec4<u32>(dot4U8Packed(ah.z, bl.x), dot4U8Packed(ah.z, bl.y), dot4U8Packed(ah.z, bl.z), dot4U8Packed(ah.z, bl.w));
                acc6h = acc6h + vec4<u32>(dot4U8Packed(ah.z, bh.x), dot4U8Packed(ah.z, bh.y), dot4U8Packed(ah.z, bh.z), dot4U8Packed(ah.z, bh.w));
                acc7l = acc7l + vec4<u32>(dot4U8Packed(ah.w, bl.x), dot4U8Packed(ah.w, bl.y), dot4U8Packed(ah.w, bl.z), dot4U8Packed(ah.w, bl.w));
                acc7h = acc7h + vec4<u32>(dot4U8Packed(ah.w, bh.x), dot4U8Packed(ah.w, bh.y), dot4U8Packed(ah.w, bh.z), dot4U8Packed(ah.w, bh.w));
            }
            {
                let al = qs[192u + ty];
                let ah = qs[208u + ty];
                let bl = ts[192u + tx];
                let bh = ts[208u + tx];
                acc0l = acc0l + vec4<u32>(dot4U8Packed(al.x, bl.x), dot4U8Packed(al.x, bl.y), dot4U8Packed(al.x, bl.z), dot4U8Packed(al.x, bl.w));
                acc0h = acc0h + vec4<u32>(dot4U8Packed(al.x, bh.x), dot4U8Packed(al.x, bh.y), dot4U8Packed(al.x, bh.z), dot4U8Packed(al.x, bh.w));
                acc1l = acc1l + vec4<u32>(dot4U8Packed(al.y, bl.x), dot4U8Packed(al.y, bl.y), dot4U8Packed(al.y, bl.z), dot4U8Packed(al.y, bl.w));
                acc1h = acc1h + vec4<u32>(dot4U8Packed(al.y, bh.x), dot4U8Packed(al.y, bh.y), dot4U8Packed(al.y, bh.z), dot4U8Packed(al.y, bh.w));
                acc2l = acc2l + vec4<u32>(dot4U8Packed(al.z, bl.x), dot4U8Packed(al.z, bl.y), dot4U8Packed(al.z, bl.z), dot4U8Packed(al.z, bl.w));
                acc2h = acc2h + vec4<u32>(dot4U8Packed(al.z, bh.x), dot4U8Packed(al.z, bh.y), dot4U8Packed(al.z, bh.z), dot4U8Packed(al.z, bh.w));
                acc3l = acc3l + vec4<u32>(dot4U8Packed(al.w, bl.x), dot4U8Packed(al.w, bl.y), dot4U8Packed(al.w, bl.z), dot4U8Packed(al.w, bl.w));
                acc3h = acc3h + vec4<u32>(dot4U8Packed(al.w, bh.x), dot4U8Packed(al.w, bh.y), dot4U8Packed(al.w, bh.z), dot4U8Packed(al.w, bh.w));
                acc4l = acc4l + vec4<u32>(dot4U8Packed(ah.x, bl.x), dot4U8Packed(ah.x, bl.y), dot4U8Packed(ah.x, bl.z), dot4U8Packed(ah.x, bl.w));
                acc4h = acc4h + vec4<u32>(dot4U8Packed(ah.x, bh.x), dot4U8Packed(ah.x, bh.y), dot4U8Packed(ah.x, bh.z), dot4U8Packed(ah.x, bh.w));
                acc5l = acc5l + vec4<u32>(dot4U8Packed(ah.y, bl.x), dot4U8Packed(ah.y, bl.y), dot4U8Packed(ah.y, bl.z), dot4U8Packed(ah.y, bl.w));
                acc5h = acc5h + vec4<u32>(dot4U8Packed(ah.y, bh.x), dot4U8Packed(ah.y, bh.y), dot4U8Packed(ah.y, bh.z), dot4U8Packed(ah.y, bh.w));
                acc6l = acc6l + vec4<u32>(dot4U8Packed(ah.z, bl.x), dot4U8Packed(ah.z, bl.y), dot4U8Packed(ah.z, bl.z), dot4U8Packed(ah.z, bl.w));
                acc6h = acc6h + vec4<u32>(dot4U8Packed(ah.z, bh.x), dot4U8Packed(ah.z, bh.y), dot4U8Packed(ah.z, bh.z), dot4U8Packed(ah.z, bh.w));
                acc7l = acc7l + vec4<u32>(dot4U8Packed(ah.w, bl.x), dot4U8Packed(ah.w, bl.y), dot4U8Packed(ah.w, bl.z), dot4U8Packed(ah.w, bl.w));
                acc7h = acc7h + vec4<u32>(dot4U8Packed(ah.w, bh.x), dot4U8Packed(ah.w, bh.y), dot4U8Packed(ah.w, bh.z), dot4U8Packed(ah.w, bh.w));
            }
            {
                let al = qs[224u + ty];
                let ah = qs[240u + ty];
                let bl = ts[224u + tx];
                let bh = ts[240u + tx];
                acc0l = acc0l + vec4<u32>(dot4U8Packed(al.x, bl.x), dot4U8Packed(al.x, bl.y), dot4U8Packed(al.x, bl.z), dot4U8Packed(al.x, bl.w));
                acc0h = acc0h + vec4<u32>(dot4U8Packed(al.x, bh.x), dot4U8Packed(al.x, bh.y), dot4U8Packed(al.x, bh.z), dot4U8Packed(al.x, bh.w));
                acc1l = acc1l + vec4<u32>(dot4U8Packed(al.y, bl.x), dot4U8Packed(al.y, bl.y), dot4U8Packed(al.y, bl.z), dot4U8Packed(al.y, bl.w));
                acc1h = acc1h + vec4<u32>(dot4U8Packed(al.y, bh.x), dot4U8Packed(al.y, bh.y), dot4U8Packed(al.y, bh.z), dot4U8Packed(al.y, bh.w));
                acc2l = acc2l + vec4<u32>(dot4U8Packed(al.z, bl.x), dot4U8Packed(al.z, bl.y), dot4U8Packed(al.z, bl.z), dot4U8Packed(al.z, bl.w));
                acc2h = acc2h + vec4<u32>(dot4U8Packed(al.z, bh.x), dot4U8Packed(al.z, bh.y), dot4U8Packed(al.z, bh.z), dot4U8Packed(al.z, bh.w));
                acc3l = acc3l + vec4<u32>(dot4U8Packed(al.w, bl.x), dot4U8Packed(al.w, bl.y), dot4U8Packed(al.w, bl.z), dot4U8Packed(al.w, bl.w));
                acc3h = acc3h + vec4<u32>(dot4U8Packed(al.w, bh.x), dot4U8Packed(al.w, bh.y), dot4U8Packed(al.w, bh.z), dot4U8Packed(al.w, bh.w));
                acc4l = acc4l + vec4<u32>(dot4U8Packed(ah.x, bl.x), dot4U8Packed(ah.x, bl.y), dot4U8Packed(ah.x, bl.z), dot4U8Packed(ah.x, bl.w));
                acc4h = acc4h + vec4<u32>(dot4U8Packed(ah.x, bh.x), dot4U8Packed(ah.x, bh.y), dot4U8Packed(ah.x, bh.z), dot4U8Packed(ah.x, bh.w));
                acc5l = acc5l + vec4<u32>(dot4U8Packed(ah.y, bl.x), dot4U8Packed(ah.y, bl.y), dot4U8Packed(ah.y, bl.z), dot4U8Packed(ah.y, bl.w));
                acc5h = acc5h + vec4<u32>(dot4U8Packed(ah.y, bh.x), dot4U8Packed(ah.y, bh.y), dot4U8Packed(ah.y, bh.z), dot4U8Packed(ah.y, bh.w));
                acc6l = acc6l + vec4<u32>(dot4U8Packed(ah.z, bl.x), dot4U8Packed(ah.z, bl.y), dot4U8Packed(ah.z, bl.z), dot4U8Packed(ah.z, bl.w));
                acc6h = acc6h + vec4<u32>(dot4U8Packed(ah.z, bh.x), dot4U8Packed(ah.z, bh.y), dot4U8Packed(ah.z, bh.z), dot4U8Packed(ah.z, bh.w));
                acc7l = acc7l + vec4<u32>(dot4U8Packed(ah.w, bl.x), dot4U8Packed(ah.w, bl.y), dot4U8Packed(ah.w, bl.z), dot4U8Packed(ah.w, bl.w));
                acc7h = acc7h + vec4<u32>(dot4U8Packed(ah.w, bh.x), dot4U8Packed(ah.w, bh.y), dot4U8Packed(ah.w, bh.z), dot4U8Packed(ah.w, bh.w));
            }
            {
                let al = qs[256u + ty];
                let ah = qs[272u + ty];
                let bl = ts[256u + tx];
                let bh = ts[272u + tx];
                acc0l = acc0l + vec4<u32>(dot4U8Packed(al.x, bl.x), dot4U8Packed(al.x, bl.y), dot4U8Packed(al.x, bl.z), dot4U8Packed(al.x, bl.w));
                acc0h = acc0h + vec4<u32>(dot4U8Packed(al.x, bh.x), dot4U8Packed(al.x, bh.y), dot4U8Packed(al.x, bh.z), dot4U8Packed(al.x, bh.w));
                acc1l = acc1l + vec4<u32>(dot4U8Packed(al.y, bl.x), dot4U8Packed(al.y, bl.y), dot4U8Packed(al.y, bl.z), dot4U8Packed(al.y, bl.w));
                acc1h = acc1h + vec4<u32>(dot4U8Packed(al.y, bh.x), dot4U8Packed(al.y, bh.y), dot4U8Packed(al.y, bh.z), dot4U8Packed(al.y, bh.w));
                acc2l = acc2l + vec4<u32>(dot4U8Packed(al.z, bl.x), dot4U8Packed(al.z, bl.y), dot4U8Packed(al.z, bl.z), dot4U8Packed(al.z, bl.w));
                acc2h = acc2h + vec4<u32>(dot4U8Packed(al.z, bh.x), dot4U8Packed(al.z, bh.y), dot4U8Packed(al.z, bh.z), dot4U8Packed(al.z, bh.w));
                acc3l = acc3l + vec4<u32>(dot4U8Packed(al.w, bl.x), dot4U8Packed(al.w, bl.y), dot4U8Packed(al.w, bl.z), dot4U8Packed(al.w, bl.w));
                acc3h = acc3h + vec4<u32>(dot4U8Packed(al.w, bh.x), dot4U8Packed(al.w, bh.y), dot4U8Packed(al.w, bh.z), dot4U8Packed(al.w, bh.w));
                acc4l = acc4l + vec4<u32>(dot4U8Packed(ah.x, bl.x), dot4U8Packed(ah.x, bl.y), dot4U8Packed(ah.x, bl.z), dot4U8Packed(ah.x, bl.w));
                acc4h = acc4h + vec4<u32>(dot4U8Packed(ah.x, bh.x), dot4U8Packed(ah.x, bh.y), dot4U8Packed(ah.x, bh.z), dot4U8Packed(ah.x, bh.w));
                acc5l = acc5l + vec4<u32>(dot4U8Packed(ah.y, bl.x), dot4U8Packed(ah.y, bl.y), dot4U8Packed(ah.y, bl.z), dot4U8Packed(ah.y, bl.w));
                acc5h = acc5h + vec4<u32>(dot4U8Packed(ah.y, bh.x), dot4U8Packed(ah.y, bh.y), dot4U8Packed(ah.y, bh.z), dot4U8Packed(ah.y, bh.w));
                acc6l = acc6l + vec4<u32>(dot4U8Packed(ah.z, bl.x), dot4U8Packed(ah.z, bl.y), dot4U8Packed(ah.z, bl.z), dot4U8Packed(ah.z, bl.w));
                acc6h = acc6h + vec4<u32>(dot4U8Packed(ah.z, bh.x), dot4U8Packed(ah.z, bh.y), dot4U8Packed(ah.z, bh.z), dot4U8Packed(ah.z, bh.w));
                acc7l = acc7l + vec4<u32>(dot4U8Packed(ah.w, bl.x), dot4U8Packed(ah.w, bl.y), dot4U8Packed(ah.w, bl.z), dot4U8Packed(ah.w, bl.w));
                acc7h = acc7h + vec4<u32>(dot4U8Packed(ah.w, bh.x), dot4U8Packed(ah.w, bh.y), dot4U8Packed(ah.w, bh.z), dot4U8Packed(ah.w, bh.w));
            }
            {
                let al = qs[288u + ty];
                let ah = qs[304u + ty];
                let bl = ts[288u + tx];
                let bh = ts[304u + tx];
                acc0l = acc0l + vec4<u32>(dot4U8Packed(al.x, bl.x), dot4U8Packed(al.x, bl.y), dot4U8Packed(al.x, bl.z), dot4U8Packed(al.x, bl.w));
                acc0h = acc0h + vec4<u32>(dot4U8Packed(al.x, bh.x), dot4U8Packed(al.x, bh.y), dot4U8Packed(al.x, bh.z), dot4U8Packed(al.x, bh.w));
                acc1l = acc1l + vec4<u32>(dot4U8Packed(al.y, bl.x), dot4U8Packed(al.y, bl.y), dot4U8Packed(al.y, bl.z), dot4U8Packed(al.y, bl.w));
                acc1h = acc1h + vec4<u32>(dot4U8Packed(al.y, bh.x), dot4U8Packed(al.y, bh.y), dot4U8Packed(al.y, bh.z), dot4U8Packed(al.y, bh.w));
                acc2l = acc2l + vec4<u32>(dot4U8Packed(al.z, bl.x), dot4U8Packed(al.z, bl.y), dot4U8Packed(al.z, bl.z), dot4U8Packed(al.z, bl.w));
                acc2h = acc2h + vec4<u32>(dot4U8Packed(al.z, bh.x), dot4U8Packed(al.z, bh.y), dot4U8Packed(al.z, bh.z), dot4U8Packed(al.z, bh.w));
                acc3l = acc3l + vec4<u32>(dot4U8Packed(al.w, bl.x), dot4U8Packed(al.w, bl.y), dot4U8Packed(al.w, bl.z), dot4U8Packed(al.w, bl.w));
                acc3h = acc3h + vec4<u32>(dot4U8Packed(al.w, bh.x), dot4U8Packed(al.w, bh.y), dot4U8Packed(al.w, bh.z), dot4U8Packed(al.w, bh.w));
                acc4l = acc4l + vec4<u32>(dot4U8Packed(ah.x, bl.x), dot4U8Packed(ah.x, bl.y), dot4U8Packed(ah.x, bl.z), dot4U8Packed(ah.x, bl.w));
                acc4h = acc4h + vec4<u32>(dot4U8Packed(ah.x, bh.x), dot4U8Packed(ah.x, bh.y), dot4U8Packed(ah.x, bh.z), dot4U8Packed(ah.x, bh.w));
                acc5l = acc5l + vec4<u32>(dot4U8Packed(ah.y, bl.x), dot4U8Packed(ah.y, bl.y), dot4U8Packed(ah.y, bl.z), dot4U8Packed(ah.y, bl.w));
                acc5h = acc5h + vec4<u32>(dot4U8Packed(ah.y, bh.x), dot4U8Packed(ah.y, bh.y), dot4U8Packed(ah.y, bh.z), dot4U8Packed(ah.y, bh.w));
                acc6l = acc6l + vec4<u32>(dot4U8Packed(ah.z, bl.x), dot4U8Packed(ah.z, bl.y), dot4U8Packed(ah.z, bl.z), dot4U8Packed(ah.z, bl.w));
                acc6h = acc6h + vec4<u32>(dot4U8Packed(ah.z, bh.x), dot4U8Packed(ah.z, bh.y), dot4U8Packed(ah.z, bh.z), dot4U8Packed(ah.z, bh.w));
                acc7l = acc7l + vec4<u32>(dot4U8Packed(ah.w, bl.x), dot4U8Packed(ah.w, bl.y), dot4U8Packed(ah.w, bl.z), dot4U8Packed(ah.w, bl.w));
                acc7h = acc7h + vec4<u32>(dot4U8Packed(ah.w, bh.x), dot4U8Packed(ah.w, bh.y), dot4U8Packed(ah.w, bh.z), dot4U8Packed(ah.w, bh.w));
            }
            {
                let al = qs[320u + ty];
                let ah = qs[336u + ty];
                let bl = ts[320u + tx];
                let bh = ts[336u + tx];
                acc0l = acc0l + vec4<u32>(dot4U8Packed(al.x, bl.x), dot4U8Packed(al.x, bl.y), dot4U8Packed(al.x, bl.z), dot4U8Packed(al.x, bl.w));
                acc0h = acc0h + vec4<u32>(dot4U8Packed(al.x, bh.x), dot4U8Packed(al.x, bh.y), dot4U8Packed(al.x, bh.z), dot4U8Packed(al.x, bh.w));
                acc1l = acc1l + vec4<u32>(dot4U8Packed(al.y, bl.x), dot4U8Packed(al.y, bl.y), dot4U8Packed(al.y, bl.z), dot4U8Packed(al.y, bl.w));
                acc1h = acc1h + vec4<u32>(dot4U8Packed(al.y, bh.x), dot4U8Packed(al.y, bh.y), dot4U8Packed(al.y, bh.z), dot4U8Packed(al.y, bh.w));
                acc2l = acc2l + vec4<u32>(dot4U8Packed(al.z, bl.x), dot4U8Packed(al.z, bl.y), dot4U8Packed(al.z, bl.z), dot4U8Packed(al.z, bl.w));
                acc2h = acc2h + vec4<u32>(dot4U8Packed(al.z, bh.x), dot4U8Packed(al.z, bh.y), dot4U8Packed(al.z, bh.z), dot4U8Packed(al.z, bh.w));
                acc3l = acc3l + vec4<u32>(dot4U8Packed(al.w, bl.x), dot4U8Packed(al.w, bl.y), dot4U8Packed(al.w, bl.z), dot4U8Packed(al.w, bl.w));
                acc3h = acc3h + vec4<u32>(dot4U8Packed(al.w, bh.x), dot4U8Packed(al.w, bh.y), dot4U8Packed(al.w, bh.z), dot4U8Packed(al.w, bh.w));
                acc4l = acc4l + vec4<u32>(dot4U8Packed(ah.x, bl.x), dot4U8Packed(ah.x, bl.y), dot4U8Packed(ah.x, bl.z), dot4U8Packed(ah.x, bl.w));
                acc4h = acc4h + vec4<u32>(dot4U8Packed(ah.x, bh.x), dot4U8Packed(ah.x, bh.y), dot4U8Packed(ah.x, bh.z), dot4U8Packed(ah.x, bh.w));
                acc5l = acc5l + vec4<u32>(dot4U8Packed(ah.y, bl.x), dot4U8Packed(ah.y, bl.y), dot4U8Packed(ah.y, bl.z), dot4U8Packed(ah.y, bl.w));
                acc5h = acc5h + vec4<u32>(dot4U8Packed(ah.y, bh.x), dot4U8Packed(ah.y, bh.y), dot4U8Packed(ah.y, bh.z), dot4U8Packed(ah.y, bh.w));
                acc6l = acc6l + vec4<u32>(dot4U8Packed(ah.z, bl.x), dot4U8Packed(ah.z, bl.y), dot4U8Packed(ah.z, bl.z), dot4U8Packed(ah.z, bl.w));
                acc6h = acc6h + vec4<u32>(dot4U8Packed(ah.z, bh.x), dot4U8Packed(ah.z, bh.y), dot4U8Packed(ah.z, bh.z), dot4U8Packed(ah.z, bh.w));
                acc7l = acc7l + vec4<u32>(dot4U8Packed(ah.w, bl.x), dot4U8Packed(ah.w, bl.y), dot4U8Packed(ah.w, bl.z), dot4U8Packed(ah.w, bl.w));
                acc7h = acc7h + vec4<u32>(dot4U8Packed(ah.w, bh.x), dot4U8Packed(ah.w, bh.y), dot4U8Packed(ah.w, bh.z), dot4U8Packed(ah.w, bh.w));
            }
            {
                let al = qs[352u + ty];
                let ah = qs[368u + ty];
                let bl = ts[352u + tx];
                let bh = ts[368u + tx];
                acc0l = acc0l + vec4<u32>(dot4U8Packed(al.x, bl.x), dot4U8Packed(al.x, bl.y), dot4U8Packed(al.x, bl.z), dot4U8Packed(al.x, bl.w));
                acc0h = acc0h + vec4<u32>(dot4U8Packed(al.x, bh.x), dot4U8Packed(al.x, bh.y), dot4U8Packed(al.x, bh.z), dot4U8Packed(al.x, bh.w));
                acc1l = acc1l + vec4<u32>(dot4U8Packed(al.y, bl.x), dot4U8Packed(al.y, bl.y), dot4U8Packed(al.y, bl.z), dot4U8Packed(al.y, bl.w));
                acc1h = acc1h + vec4<u32>(dot4U8Packed(al.y, bh.x), dot4U8Packed(al.y, bh.y), dot4U8Packed(al.y, bh.z), dot4U8Packed(al.y, bh.w));
                acc2l = acc2l + vec4<u32>(dot4U8Packed(al.z, bl.x), dot4U8Packed(al.z, bl.y), dot4U8Packed(al.z, bl.z), dot4U8Packed(al.z, bl.w));
                acc2h = acc2h + vec4<u32>(dot4U8Packed(al.z, bh.x), dot4U8Packed(al.z, bh.y), dot4U8Packed(al.z, bh.z), dot4U8Packed(al.z, bh.w));
                acc3l = acc3l + vec4<u32>(dot4U8Packed(al.w, bl.x), dot4U8Packed(al.w, bl.y), dot4U8Packed(al.w, bl.z), dot4U8Packed(al.w, bl.w));
                acc3h = acc3h + vec4<u32>(dot4U8Packed(al.w, bh.x), dot4U8Packed(al.w, bh.y), dot4U8Packed(al.w, bh.z), dot4U8Packed(al.w, bh.w));
                acc4l = acc4l + vec4<u32>(dot4U8Packed(ah.x, bl.x), dot4U8Packed(ah.x, bl.y), dot4U8Packed(ah.x, bl.z), dot4U8Packed(ah.x, bl.w));
                acc4h = acc4h + vec4<u32>(dot4U8Packed(ah.x, bh.x), dot4U8Packed(ah.x, bh.y), dot4U8Packed(ah.x, bh.z), dot4U8Packed(ah.x, bh.w));
                acc5l = acc5l + vec4<u32>(dot4U8Packed(ah.y, bl.x), dot4U8Packed(ah.y, bl.y), dot4U8Packed(ah.y, bl.z), dot4U8Packed(ah.y, bl.w));
                acc5h = acc5h + vec4<u32>(dot4U8Packed(ah.y, bh.x), dot4U8Packed(ah.y, bh.y), dot4U8Packed(ah.y, bh.z), dot4U8Packed(ah.y, bh.w));
                acc6l = acc6l + vec4<u32>(dot4U8Packed(ah.z, bl.x), dot4U8Packed(ah.z, bl.y), dot4U8Packed(ah.z, bl.z), dot4U8Packed(ah.z, bl.w));
                acc6h = acc6h + vec4<u32>(dot4U8Packed(ah.z, bh.x), dot4U8Packed(ah.z, bh.y), dot4U8Packed(ah.z, bh.z), dot4U8Packed(ah.z, bh.w));
                acc7l = acc7l + vec4<u32>(dot4U8Packed(ah.w, bl.x), dot4U8Packed(ah.w, bl.y), dot4U8Packed(ah.w, bl.z), dot4U8Packed(ah.w, bl.w));
                acc7h = acc7h + vec4<u32>(dot4U8Packed(ah.w, bh.x), dot4U8Packed(ah.w, bh.y), dot4U8Packed(ah.w, bh.z), dot4U8Packed(ah.w, bh.w));
            }
            {
                let al = qs[384u + ty];
                let ah = qs[400u + ty];
                let bl = ts[384u + tx];
                let bh = ts[400u + tx];
                acc0l = acc0l + vec4<u32>(dot4U8Packed(al.x, bl.x), dot4U8Packed(al.x, bl.y), dot4U8Packed(al.x, bl.z), dot4U8Packed(al.x, bl.w));
                acc0h = acc0h + vec4<u32>(dot4U8Packed(al.x, bh.x), dot4U8Packed(al.x, bh.y), dot4U8Packed(al.x, bh.z), dot4U8Packed(al.x, bh.w));
                acc1l = acc1l + vec4<u32>(dot4U8Packed(al.y, bl.x), dot4U8Packed(al.y, bl.y), dot4U8Packed(al.y, bl.z), dot4U8Packed(al.y, bl.w));
                acc1h = acc1h + vec4<u32>(dot4U8Packed(al.y, bh.x), dot4U8Packed(al.y, bh.y), dot4U8Packed(al.y, bh.z), dot4U8Packed(al.y, bh.w));
                acc2l = acc2l + vec4<u32>(dot4U8Packed(al.z, bl.x), dot4U8Packed(al.z, bl.y), dot4U8Packed(al.z, bl.z), dot4U8Packed(al.z, bl.w));
                acc2h = acc2h + vec4<u32>(dot4U8Packed(al.z, bh.x), dot4U8Packed(al.z, bh.y), dot4U8Packed(al.z, bh.z), dot4U8Packed(al.z, bh.w));
                acc3l = acc3l + vec4<u32>(dot4U8Packed(al.w, bl.x), dot4U8Packed(al.w, bl.y), dot4U8Packed(al.w, bl.z), dot4U8Packed(al.w, bl.w));
                acc3h = acc3h + vec4<u32>(dot4U8Packed(al.w, bh.x), dot4U8Packed(al.w, bh.y), dot4U8Packed(al.w, bh.z), dot4U8Packed(al.w, bh.w));
                acc4l = acc4l + vec4<u32>(dot4U8Packed(ah.x, bl.x), dot4U8Packed(ah.x, bl.y), dot4U8Packed(ah.x, bl.z), dot4U8Packed(ah.x, bl.w));
                acc4h = acc4h + vec4<u32>(dot4U8Packed(ah.x, bh.x), dot4U8Packed(ah.x, bh.y), dot4U8Packed(ah.x, bh.z), dot4U8Packed(ah.x, bh.w));
                acc5l = acc5l + vec4<u32>(dot4U8Packed(ah.y, bl.x), dot4U8Packed(ah.y, bl.y), dot4U8Packed(ah.y, bl.z), dot4U8Packed(ah.y, bl.w));
                acc5h = acc5h + vec4<u32>(dot4U8Packed(ah.y, bh.x), dot4U8Packed(ah.y, bh.y), dot4U8Packed(ah.y, bh.z), dot4U8Packed(ah.y, bh.w));
                acc6l = acc6l + vec4<u32>(dot4U8Packed(ah.z, bl.x), dot4U8Packed(ah.z, bl.y), dot4U8Packed(ah.z, bl.z), dot4U8Packed(ah.z, bl.w));
                acc6h = acc6h + vec4<u32>(dot4U8Packed(ah.z, bh.x), dot4U8Packed(ah.z, bh.y), dot4U8Packed(ah.z, bh.z), dot4U8Packed(ah.z, bh.w));
                acc7l = acc7l + vec4<u32>(dot4U8Packed(ah.w, bl.x), dot4U8Packed(ah.w, bl.y), dot4U8Packed(ah.w, bl.z), dot4U8Packed(ah.w, bl.w));
                acc7h = acc7h + vec4<u32>(dot4U8Packed(ah.w, bh.x), dot4U8Packed(ah.w, bh.y), dot4U8Packed(ah.w, bh.z), dot4U8Packed(ah.w, bh.w));
            }
            {
                let al = qs[416u + ty];
                let ah = qs[432u + ty];
                let bl = ts[416u + tx];
                let bh = ts[432u + tx];
                acc0l = acc0l + vec4<u32>(dot4U8Packed(al.x, bl.x), dot4U8Packed(al.x, bl.y), dot4U8Packed(al.x, bl.z), dot4U8Packed(al.x, bl.w));
                acc0h = acc0h + vec4<u32>(dot4U8Packed(al.x, bh.x), dot4U8Packed(al.x, bh.y), dot4U8Packed(al.x, bh.z), dot4U8Packed(al.x, bh.w));
                acc1l = acc1l + vec4<u32>(dot4U8Packed(al.y, bl.x), dot4U8Packed(al.y, bl.y), dot4U8Packed(al.y, bl.z), dot4U8Packed(al.y, bl.w));
                acc1h = acc1h + vec4<u32>(dot4U8Packed(al.y, bh.x), dot4U8Packed(al.y, bh.y), dot4U8Packed(al.y, bh.z), dot4U8Packed(al.y, bh.w));
                acc2l = acc2l + vec4<u32>(dot4U8Packed(al.z, bl.x), dot4U8Packed(al.z, bl.y), dot4U8Packed(al.z, bl.z), dot4U8Packed(al.z, bl.w));
                acc2h = acc2h + vec4<u32>(dot4U8Packed(al.z, bh.x), dot4U8Packed(al.z, bh.y), dot4U8Packed(al.z, bh.z), dot4U8Packed(al.z, bh.w));
                acc3l = acc3l + vec4<u32>(dot4U8Packed(al.w, bl.x), dot4U8Packed(al.w, bl.y), dot4U8Packed(al.w, bl.z), dot4U8Packed(al.w, bl.w));
                acc3h = acc3h + vec4<u32>(dot4U8Packed(al.w, bh.x), dot4U8Packed(al.w, bh.y), dot4U8Packed(al.w, bh.z), dot4U8Packed(al.w, bh.w));
                acc4l = acc4l + vec4<u32>(dot4U8Packed(ah.x, bl.x), dot4U8Packed(ah.x, bl.y), dot4U8Packed(ah.x, bl.z), dot4U8Packed(ah.x, bl.w));
                acc4h = acc4h + vec4<u32>(dot4U8Packed(ah.x, bh.x), dot4U8Packed(ah.x, bh.y), dot4U8Packed(ah.x, bh.z), dot4U8Packed(ah.x, bh.w));
                acc5l = acc5l + vec4<u32>(dot4U8Packed(ah.y, bl.x), dot4U8Packed(ah.y, bl.y), dot4U8Packed(ah.y, bl.z), dot4U8Packed(ah.y, bl.w));
                acc5h = acc5h + vec4<u32>(dot4U8Packed(ah.y, bh.x), dot4U8Packed(ah.y, bh.y), dot4U8Packed(ah.y, bh.z), dot4U8Packed(ah.y, bh.w));
                acc6l = acc6l + vec4<u32>(dot4U8Packed(ah.z, bl.x), dot4U8Packed(ah.z, bl.y), dot4U8Packed(ah.z, bl.z), dot4U8Packed(ah.z, bl.w));
                acc6h = acc6h + vec4<u32>(dot4U8Packed(ah.z, bh.x), dot4U8Packed(ah.z, bh.y), dot4U8Packed(ah.z, bh.z), dot4U8Packed(ah.z, bh.w));
                acc7l = acc7l + vec4<u32>(dot4U8Packed(ah.w, bl.x), dot4U8Packed(ah.w, bl.y), dot4U8Packed(ah.w, bl.z), dot4U8Packed(ah.w, bl.w));
                acc7h = acc7h + vec4<u32>(dot4U8Packed(ah.w, bh.x), dot4U8Packed(ah.w, bh.y), dot4U8Packed(ah.w, bh.z), dot4U8Packed(ah.w, bh.w));
            }
            {
                let al = qs[448u + ty];
                let ah = qs[464u + ty];
                let bl = ts[448u + tx];
                let bh = ts[464u + tx];
                acc0l = acc0l + vec4<u32>(dot4U8Packed(al.x, bl.x), dot4U8Packed(al.x, bl.y), dot4U8Packed(al.x, bl.z), dot4U8Packed(al.x, bl.w));
                acc0h = acc0h + vec4<u32>(dot4U8Packed(al.x, bh.x), dot4U8Packed(al.x, bh.y), dot4U8Packed(al.x, bh.z), dot4U8Packed(al.x, bh.w));
                acc1l = acc1l + vec4<u32>(dot4U8Packed(al.y, bl.x), dot4U8Packed(al.y, bl.y), dot4U8Packed(al.y, bl.z), dot4U8Packed(al.y, bl.w));
                acc1h = acc1h + vec4<u32>(dot4U8Packed(al.y, bh.x), dot4U8Packed(al.y, bh.y), dot4U8Packed(al.y, bh.z), dot4U8Packed(al.y, bh.w));
                acc2l = acc2l + vec4<u32>(dot4U8Packed(al.z, bl.x), dot4U8Packed(al.z, bl.y), dot4U8Packed(al.z, bl.z), dot4U8Packed(al.z, bl.w));
                acc2h = acc2h + vec4<u32>(dot4U8Packed(al.z, bh.x), dot4U8Packed(al.z, bh.y), dot4U8Packed(al.z, bh.z), dot4U8Packed(al.z, bh.w));
                acc3l = acc3l + vec4<u32>(dot4U8Packed(al.w, bl.x), dot4U8Packed(al.w, bl.y), dot4U8Packed(al.w, bl.z), dot4U8Packed(al.w, bl.w));
                acc3h = acc3h + vec4<u32>(dot4U8Packed(al.w, bh.x), dot4U8Packed(al.w, bh.y), dot4U8Packed(al.w, bh.z), dot4U8Packed(al.w, bh.w));
                acc4l = acc4l + vec4<u32>(dot4U8Packed(ah.x, bl.x), dot4U8Packed(ah.x, bl.y), dot4U8Packed(ah.x, bl.z), dot4U8Packed(ah.x, bl.w));
                acc4h = acc4h + vec4<u32>(dot4U8Packed(ah.x, bh.x), dot4U8Packed(ah.x, bh.y), dot4U8Packed(ah.x, bh.z), dot4U8Packed(ah.x, bh.w));
                acc5l = acc5l + vec4<u32>(dot4U8Packed(ah.y, bl.x), dot4U8Packed(ah.y, bl.y), dot4U8Packed(ah.y, bl.z), dot4U8Packed(ah.y, bl.w));
                acc5h = acc5h + vec4<u32>(dot4U8Packed(ah.y, bh.x), dot4U8Packed(ah.y, bh.y), dot4U8Packed(ah.y, bh.z), dot4U8Packed(ah.y, bh.w));
                acc6l = acc6l + vec4<u32>(dot4U8Packed(ah.z, bl.x), dot4U8Packed(ah.z, bl.y), dot4U8Packed(ah.z, bl.z), dot4U8Packed(ah.z, bl.w));
                acc6h = acc6h + vec4<u32>(dot4U8Packed(ah.z, bh.x), dot4U8Packed(ah.z, bh.y), dot4U8Packed(ah.z, bh.z), dot4U8Packed(ah.z, bh.w));
                acc7l = acc7l + vec4<u32>(dot4U8Packed(ah.w, bl.x), dot4U8Packed(ah.w, bl.y), dot4U8Packed(ah.w, bl.z), dot4U8Packed(ah.w, bl.w));
                acc7h = acc7h + vec4<u32>(dot4U8Packed(ah.w, bh.x), dot4U8Packed(ah.w, bh.y), dot4U8Packed(ah.w, bh.z), dot4U8Packed(ah.w, bh.w));
            }
            {
                let al = qs[480u + ty];
                let ah = qs[496u + ty];
                let bl = ts[480u + tx];
                let bh = ts[496u + tx];
                acc0l = acc0l + vec4<u32>(dot4U8Packed(al.x, bl.x), dot4U8Packed(al.x, bl.y), dot4U8Packed(al.x, bl.z), dot4U8Packed(al.x, bl.w));
                acc0h = acc0h + vec4<u32>(dot4U8Packed(al.x, bh.x), dot4U8Packed(al.x, bh.y), dot4U8Packed(al.x, bh.z), dot4U8Packed(al.x, bh.w));
                acc1l = acc1l + vec4<u32>(dot4U8Packed(al.y, bl.x), dot4U8Packed(al.y, bl.y), dot4U8Packed(al.y, bl.z), dot4U8Packed(al.y, bl.w));
                acc1h = acc1h + vec4<u32>(dot4U8Packed(al.y, bh.x), dot4U8Packed(al.y, bh.y), dot4U8Packed(al.y, bh.z), dot4U8Packed(al.y, bh.w));
                acc2l = acc2l + vec4<u32>(dot4U8Packed(al.z, bl.x), dot4U8Packed(al.z, bl.y), dot4U8Packed(al.z, bl.z), dot4U8Packed(al.z, bl.w));
                acc2h = acc2h + vec4<u32>(dot4U8Packed(al.z, bh.x), dot4U8Packed(al.z, bh.y), dot4U8Packed(al.z, bh.z), dot4U8Packed(al.z, bh.w));
                acc3l = acc3l + vec4<u32>(dot4U8Packed(al.w, bl.x), dot4U8Packed(al.w, bl.y), dot4U8Packed(al.w, bl.z), dot4U8Packed(al.w, bl.w));
                acc3h = acc3h + vec4<u32>(dot4U8Packed(al.w, bh.x), dot4U8Packed(al.w, bh.y), dot4U8Packed(al.w, bh.z), dot4U8Packed(al.w, bh.w));
                acc4l = acc4l + vec4<u32>(dot4U8Packed(ah.x, bl.x), dot4U8Packed(ah.x, bl.y), dot4U8Packed(ah.x, bl.z), dot4U8Packed(ah.x, bl.w));
                acc4h = acc4h + vec4<u32>(dot4U8Packed(ah.x, bh.x), dot4U8Packed(ah.x, bh.y), dot4U8Packed(ah.x, bh.z), dot4U8Packed(ah.x, bh.w));
                acc5l = acc5l + vec4<u32>(dot4U8Packed(ah.y, bl.x), dot4U8Packed(ah.y, bl.y), dot4U8Packed(ah.y, bl.z), dot4U8Packed(ah.y, bl.w));
                acc5h = acc5h + vec4<u32>(dot4U8Packed(ah.y, bh.x), dot4U8Packed(ah.y, bh.y), dot4U8Packed(ah.y, bh.z), dot4U8Packed(ah.y, bh.w));
                acc6l = acc6l + vec4<u32>(dot4U8Packed(ah.z, bl.x), dot4U8Packed(ah.z, bl.y), dot4U8Packed(ah.z, bl.z), dot4U8Packed(ah.z, bl.w));
                acc6h = acc6h + vec4<u32>(dot4U8Packed(ah.z, bh.x), dot4U8Packed(ah.z, bh.y), dot4U8Packed(ah.z, bh.z), dot4U8Packed(ah.z, bh.w));
                acc7l = acc7l + vec4<u32>(dot4U8Packed(ah.w, bl.x), dot4U8Packed(ah.w, bl.y), dot4U8Packed(ah.w, bl.z), dot4U8Packed(ah.w, bl.w));
                acc7h = acc7h + vec4<u32>(dot4U8Packed(ah.w, bh.x), dot4U8Packed(ah.w, bh.y), dot4U8Packed(ah.w, bh.z), dot4U8Packed(ah.w, bh.w));
            }
            workgroupBarrier();
        }
        {
            let col = col0 + 4u * tx + 0u;
            if (col < e.nt) {
                let tn = norms[e.t_off + col];
                r0 = insert_inc(r0, tn - 2.0 * f32(acc0l.x), col);
                r1 = insert_inc(r1, tn - 2.0 * f32(acc1l.x), col);
                r2 = insert_inc(r2, tn - 2.0 * f32(acc2l.x), col);
                r3 = insert_inc(r3, tn - 2.0 * f32(acc3l.x), col);
                r4 = insert_inc(r4, tn - 2.0 * f32(acc4l.x), col);
                r5 = insert_inc(r5, tn - 2.0 * f32(acc5l.x), col);
                r6 = insert_inc(r6, tn - 2.0 * f32(acc6l.x), col);
                r7 = insert_inc(r7, tn - 2.0 * f32(acc7l.x), col);
            }
        }
        {
            let col = col0 + 4u * tx + 1u;
            if (col < e.nt) {
                let tn = norms[e.t_off + col];
                r0 = insert_inc(r0, tn - 2.0 * f32(acc0l.y), col);
                r1 = insert_inc(r1, tn - 2.0 * f32(acc1l.y), col);
                r2 = insert_inc(r2, tn - 2.0 * f32(acc2l.y), col);
                r3 = insert_inc(r3, tn - 2.0 * f32(acc3l.y), col);
                r4 = insert_inc(r4, tn - 2.0 * f32(acc4l.y), col);
                r5 = insert_inc(r5, tn - 2.0 * f32(acc5l.y), col);
                r6 = insert_inc(r6, tn - 2.0 * f32(acc6l.y), col);
                r7 = insert_inc(r7, tn - 2.0 * f32(acc7l.y), col);
            }
        }
        {
            let col = col0 + 4u * tx + 2u;
            if (col < e.nt) {
                let tn = norms[e.t_off + col];
                r0 = insert_inc(r0, tn - 2.0 * f32(acc0l.z), col);
                r1 = insert_inc(r1, tn - 2.0 * f32(acc1l.z), col);
                r2 = insert_inc(r2, tn - 2.0 * f32(acc2l.z), col);
                r3 = insert_inc(r3, tn - 2.0 * f32(acc3l.z), col);
                r4 = insert_inc(r4, tn - 2.0 * f32(acc4l.z), col);
                r5 = insert_inc(r5, tn - 2.0 * f32(acc5l.z), col);
                r6 = insert_inc(r6, tn - 2.0 * f32(acc6l.z), col);
                r7 = insert_inc(r7, tn - 2.0 * f32(acc7l.z), col);
            }
        }
        {
            let col = col0 + 4u * tx + 3u;
            if (col < e.nt) {
                let tn = norms[e.t_off + col];
                r0 = insert_inc(r0, tn - 2.0 * f32(acc0l.w), col);
                r1 = insert_inc(r1, tn - 2.0 * f32(acc1l.w), col);
                r2 = insert_inc(r2, tn - 2.0 * f32(acc2l.w), col);
                r3 = insert_inc(r3, tn - 2.0 * f32(acc3l.w), col);
                r4 = insert_inc(r4, tn - 2.0 * f32(acc4l.w), col);
                r5 = insert_inc(r5, tn - 2.0 * f32(acc5l.w), col);
                r6 = insert_inc(r6, tn - 2.0 * f32(acc6l.w), col);
                r7 = insert_inc(r7, tn - 2.0 * f32(acc7l.w), col);
            }
        }
        {
            let col = col0 + 64u + 4u * tx + 0u;
            if (col < e.nt) {
                let tn = norms[e.t_off + col];
                r0 = insert_inc(r0, tn - 2.0 * f32(acc0h.x), col);
                r1 = insert_inc(r1, tn - 2.0 * f32(acc1h.x), col);
                r2 = insert_inc(r2, tn - 2.0 * f32(acc2h.x), col);
                r3 = insert_inc(r3, tn - 2.0 * f32(acc3h.x), col);
                r4 = insert_inc(r4, tn - 2.0 * f32(acc4h.x), col);
                r5 = insert_inc(r5, tn - 2.0 * f32(acc5h.x), col);
                r6 = insert_inc(r6, tn - 2.0 * f32(acc6h.x), col);
                r7 = insert_inc(r7, tn - 2.0 * f32(acc7h.x), col);
            }
        }
        {
            let col = col0 + 64u + 4u * tx + 1u;
            if (col < e.nt) {
                let tn = norms[e.t_off + col];
                r0 = insert_inc(r0, tn - 2.0 * f32(acc0h.y), col);
                r1 = insert_inc(r1, tn - 2.0 * f32(acc1h.y), col);
                r2 = insert_inc(r2, tn - 2.0 * f32(acc2h.y), col);
                r3 = insert_inc(r3, tn - 2.0 * f32(acc3h.y), col);
                r4 = insert_inc(r4, tn - 2.0 * f32(acc4h.y), col);
                r5 = insert_inc(r5, tn - 2.0 * f32(acc5h.y), col);
                r6 = insert_inc(r6, tn - 2.0 * f32(acc6h.y), col);
                r7 = insert_inc(r7, tn - 2.0 * f32(acc7h.y), col);
            }
        }
        {
            let col = col0 + 64u + 4u * tx + 2u;
            if (col < e.nt) {
                let tn = norms[e.t_off + col];
                r0 = insert_inc(r0, tn - 2.0 * f32(acc0h.z), col);
                r1 = insert_inc(r1, tn - 2.0 * f32(acc1h.z), col);
                r2 = insert_inc(r2, tn - 2.0 * f32(acc2h.z), col);
                r3 = insert_inc(r3, tn - 2.0 * f32(acc3h.z), col);
                r4 = insert_inc(r4, tn - 2.0 * f32(acc4h.z), col);
                r5 = insert_inc(r5, tn - 2.0 * f32(acc5h.z), col);
                r6 = insert_inc(r6, tn - 2.0 * f32(acc6h.z), col);
                r7 = insert_inc(r7, tn - 2.0 * f32(acc7h.z), col);
            }
        }
        {
            let col = col0 + 64u + 4u * tx + 3u;
            if (col < e.nt) {
                let tn = norms[e.t_off + col];
                r0 = insert_inc(r0, tn - 2.0 * f32(acc0h.w), col);
                r1 = insert_inc(r1, tn - 2.0 * f32(acc1h.w), col);
                r2 = insert_inc(r2, tn - 2.0 * f32(acc2h.w), col);
                r3 = insert_inc(r3, tn - 2.0 * f32(acc3h.w), col);
                r4 = insert_inc(r4, tn - 2.0 * f32(acc4h.w), col);
                r5 = insert_inc(r5, tn - 2.0 * f32(acc5h.w), col);
                r6 = insert_inc(r6, tn - 2.0 * f32(acc6h.w), col);
                r7 = insert_inc(r7, tn - 2.0 * f32(acc7h.w), col);
            }
        }
    }

    // Reduce the 16 column-threads of each row: (row, tx) partials.
    store((4u * ty + 0u) * 16u + tx, r0);
    store((4u * ty + 1u) * 16u + tx, r1);
    store((4u * ty + 2u) * 16u + tx, r2);
    store((4u * ty + 3u) * 16u + tx, r3);
    store((64u + 4u * ty + 0u) * 16u + tx, r4);
    store((64u + 4u * ty + 1u) * 16u + tx, r5);
    store((64u + 4u * ty + 2u) * 16u + tx, r6);
    store((64u + 4u * ty + 3u) * 16u + tx, r7);
    workgroupBarrier();
    if (t < 128u && row0 + t < e.nq) {
        var r = Top2(BIG, NONE, BIG, NONE);
        for (var x = 0u; x < 16u; x = x + 1u) {
            r = fold(r, t * 16u + x);
        }
        out[e.out_off + row0 + t] = vec4<u32>(r.i1, bitcast<u32>(r.s1), bitcast<u32>(r.s2), r.i2);
    }
}
