[package]
name = "visloc-vision"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description.workspace = true
readme.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
nalgebra = { workspace = true }
rand = { workspace = true }
visloc-core = { path = "../core", version = "0.1.0" }
