[package]
name = "visloc-vision"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Feature, matching, PnP, RANSAC, and pose-refinement building blocks for visloc-rs."
readme.workspace = true
documentation = "https://docs.rs/visloc-vision"
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
nalgebra = { workspace = true }
rand = { workspace = true }
visloc-core = { path = "../core", version = "0.1.0" }
