#!/usr/bin/env python3
"""Generate crates/sift-gpu/src/shaders/match.wgsl (and, with --u8,
match_u8.wgsl), the batched GPU top-2
descriptor matcher, fully unrolled.

    python3 scripts/gen_match_wgsl.py > crates/sift-gpu/src/shaders/match.wgsl
    python3 scripts/gen_match_wgsl.py --u8 > crates/sift-gpu/src/shaders/match_u8.wgsl

Any change must keep the matches bit-identical: every dot product sums
k = 0..dim in order, and ties go to the lower index. Check with the digest
printed by `cargo run --release -p visloc-sift-gpu --features gpu --example
match_gpu_bench`.
"""

import sys

HEADER = '''// GENERATED by scripts/gen_match_wgsl.py -- edit that script, not this file.
//
// Batched brute-force top-2 nearest neighbours over a device-resident
// descriptor bank (the GPU half of visloc-vision's `BruteForceMatcher`).
//
// Each entry names a query block and a train block of the bank; for every
// query row it finds the two smallest scores ||t||^2 - 2 q.t (= ||q - t||^2
// - ||q||^2, the CPU matcher's ranking) and the best train index. Ties go
// to the lower index, like the CPU's strict `<` scan. The host turns
// scores into distances, applies the ratio test and cross-checks with the
// swapped entry.
//
// One workgroup = 128 query rows x all train rows of one entry, in 128-row
// train tiles; a classic shared-memory GEMM with 16-wide k chunks (the k
// loop unrolled), each thread holding an 8 x 8 register tile (rows 4 ty + i
// and 64 + 4 ty + i, cols 4 tx + j and 64 + 4 tx + j) so every operand read
// out of shared memory is one vec4. Every dot product still sums
// k = 0..dim in order.
//
// Each thread offers its candidates to its own running top-2 in increasing
// index order, so there the index tie-break can never fire and `insert_inc`
// skips it; the folds across threads use the full `insert`.
//
// Cross-check needs the reverse top-2 as well (per train column over all
// query rows, score ||q||^2 - 2 q.t). The same dot tile gives it: each
// workgroup writes a per-column partial top-2 over its 128 rows to
// `rev_part`, and `rev_reduce` folds the row blocks. The dot products are
// bit-identical to computing the swapped entry, so the result is too.

struct MatchParams {
    // vec4s per descriptor row (dim / 4); dim is a multiple of 32.
    dim4: u32,
    num_entries: u32,
    pad0: u32,
    pad1: u32,
};

struct Entry {
    q_off: u32,
    nq: u32,
    t_off: u32,
    nt: u32,
    out_off: u32,
    // Reverse top-2: partials at rev_part[rev_part_off + block * nt + col],
    // results at out[rev_out_off + col]. rev_out_off == NONE: forward only.
    rev_part_off: u32,
    rev_out_off: u32,
    pad0: u32,
};

@group(0) @binding(0) var<uniform> p: MatchParams;
@group(0) @binding(1) var<storage, read> desc: array<vec4<f32>>;
@group(0) @binding(2) var<storage, read> norms: array<f32>;
@group(0) @binding(3) var<storage, read> entries: array<Entry>;
// Per query row: best index, best score, second score, second index.
@group(0) @binding(4) var<storage, read_write> out: array<vec4<u32>>;
@group(0) @binding(5) var<storage, read_write> rev_part: array<vec4<u32>>;

const BIG: f32 = 3.0e38;
const NONE: u32 = 0xFFFFFFFFu;

// k-major tiles, four consecutive rows per vec4: qs[k * 32 + row / 4][row % 4].
// After the GEMM they double as score scratch for the top-2 folds.
var<workgroup> qs: array<vec4<f32>, 512>;
var<workgroup> ts: array<vec4<f32>, 512>;
var<workgroup> red_i1: array<u32, 2048>;
var<workgroup> red_i2: array<u32, 2048>;

struct Top2 {
    s1: f32,
    i1: u32,
    s2: f32,
    i2: u32,
};

fn before(sa: f32, ia: u32, sb: f32, ib: u32) -> bool {
    return sa < sb || (sa == sb && ia < ib);
}

// Branch-free: the same result as "new best, else new second".
fn insert(t: Top2, s: f32, i: u32) -> Top2 {
    let b1 = before(s, i, t.s1, t.i1);
    let b2 = before(s, i, t.s2, t.i2);
    return Top2(
        select(t.s1, s, b1),
        select(t.i1, i, b1),
        select(select(t.s2, s, b2), t.s1, b1),
        select(select(t.i2, i, b2), t.i1, b1),
    );
}

// `insert` for an index above every index already inserted: an equal score
// then never wins, so plain `<` gives the same scores and best index. The
// second index is dropped (NONE): it only breaks ties between equal second
// scores, which leaves the second score itself unchanged.
fn insert_inc(t: Top2, s: f32, i: u32) -> Top2 {
    let b1 = s < t.s1;
    let b2 = s < t.s2;
    return Top2(
        select(t.s1, s, b1),
        select(t.i1, i, b1),
        select(select(t.s2, s, b2), t.s1, b1),
        NONE,
    );
}

// Fold shared-memory partial `slot` (scores in qs/ts, indices in red_i*).
fn fold(c: Top2, slot: u32) -> Top2 {
    let r = insert(c, qs[slot / 4u][slot % 4u], red_i1[slot]);
    return insert(r, ts[slot / 4u][slot % 4u], red_i2[slot]);
}

fn store(slot: u32, c: Top2) {
    qs[slot / 4u][slot % 4u] = c.s1;
    ts[slot / 4u][slot % 4u] = c.s2;
    red_i1[slot] = c.i1;
    red_i2[slot] = c.i2;
}

// One vec4 of a 128-row x 16-k tile (512 vec4, two per thread): fetch it
// from the bank, then put it into the k-major shared tile.
fn fetch(row_off: u32, nrows: u32, row0: u32, kc: u32, t: u32, s: u32) -> vec4<f32> {
    let idx = t + 256u * s;
    let row = idx / 4u;
    let v = idx % 4u;
    if (row0 + row < nrows) {
        return desc[(row_off + row0 + row) * p.dim4 + kc * 4u + v];
    }
    return vec4<f32>(0.0);
}

fn put(dst_is_q: bool, t: u32, s: u32, val: vec4<f32>) {
    let idx = t + 256u * s;
    let row = idx / 4u;
    let v = idx % 4u;
    let base = v * 4u * 32u + row / 4u;
    let c = row % 4u;
    if (dst_is_q) {
        qs[base][c] = val.x;
        qs[base + 32u][c] = val.y;
        qs[base + 64u][c] = val.z;
        qs[base + 96u][c] = val.w;
    } else {
        ts[base][c] = val.x;
        ts[base + 32u][c] = val.y;
        ts[base + 64u][c] = val.z;
        ts[base + 96u][c] = val.w;
    }
}
'''

REV_REDUCE = '''
// Fold the per-row-block column partials of `top2` into the reverse top-2.
@compute @workgroup_size(64)
fn rev_reduce(@builtin(global_invocation_id) gid: vec3<u32>, @builtin(workgroup_id) wid: vec3<u32>) {
    let e = entries[wid.y];
    let col = gid.x;
    if (e.rev_out_off == NONE || col >= e.nt) {
        return;
    }
    let nblk = (e.nq + 127u) / 128u;
    var c = Top2(BIG, NONE, BIG, NONE);
    for (var b = 0u; b < nblk; b = b + 1u) {
        let w = rev_part[e.rev_part_off + b * e.nt + col];
        c = insert(c, bitcast<f32>(w.y), w.x);
        c = insert(c, bitcast<f32>(w.z), w.w);
    }
    out[e.rev_out_off + col] = vec4<u32>(c.i1, bitcast<u32>(c.s1), bitcast<u32>(c.s2), c.i2);
}
'''

# The thread's 8 rows and 8 columns of the 128 x 128 tile; register r / c
# holds row ROWS[r] / column COLS[c] (acc{r}l covers the low four columns,
# acc{r}h the high four).
ROWS = [f'row0 + {"64u + " if r >= 4 else ""}4u * ty + {r % 4}u' for r in range(8)]
COLS = [f'col0 + {"64u + " if c >= 4 else ""}4u * tx + {c % 4}u' for c in range(8)]
LANE = [('l', 'h')[c // 4] + '.' + 'xyzw'[c % 4] for c in range(8)]
A = [('al', 'ah')[r // 4] + '.' + 'xyzw'[r % 4] for r in range(8)]


def dot(r, c):
    """Dot product of register row r and column c as f32 (exact for u8:
    integers below 2^24)."""
    acc = f'acc{r}{LANE[c]}'
    return f'f32({acc})' if U8 else acc


def u8_header(h):
    """The f32 header retargeted to packed u8 descriptors: 4 bytes per u32,
    a vec4<u32> holds 16 descriptor bytes, and the shared tiles store scores
    as bit patterns during the folds."""
    reps = [
        ('var<storage, read> desc: array<vec4<f32>>;', 'var<storage, read> desc: array<vec4<u32>>;'),
        ('var<workgroup> qs: array<vec4<f32>, 512>;', 'var<workgroup> qs: array<vec4<u32>, 512>;'),
        ('var<workgroup> ts: array<vec4<f32>, 512>;', 'var<workgroup> ts: array<vec4<u32>, 512>;'),
        ('t: u32, s: u32) -> vec4<f32> {', 't: u32, s: u32) -> vec4<u32> {'),
        ('    return vec4<f32>(0.0);\n}', '    return vec4<u32>(0u);\n}'),
        ('s: u32, val: vec4<f32>) {', 's: u32, val: vec4<u32>) {'),
        ('insert(c, qs[slot / 4u][slot % 4u], red_i1[slot])', 'insert(c, bitcast<f32>(qs[slot / 4u][slot % 4u]), red_i1[slot])'),
        ('insert(r, ts[slot / 4u][slot % 4u], red_i2[slot])', 'insert(r, bitcast<f32>(ts[slot / 4u][slot % 4u]), red_i2[slot])'),
        ('qs[slot / 4u][slot % 4u] = c.s1;', 'qs[slot / 4u][slot % 4u] = bitcast<u32>(c.s1);'),
        ('ts[slot / 4u][slot % 4u] = c.s2;', 'ts[slot / 4u][slot % 4u] = bitcast<u32>(c.s2);'),
        ('    // vec4s per descriptor row (dim / 4); dim is a multiple of 32.', '    // vec4<u32>s per descriptor row (dim / 16); dim is a multiple of 64.'),
        ('@group(0) @binding(5) var<storage, read_write> rev_part: array<vec4<u32>>;\n', ''),
    ]
    for a, b in reps:
        assert a in h, a
        h = h.replace(a, b)
    first = h.index('\n//\n')
    return (h[:first] + '''
//
// u8 variant: descriptors quantised COLMAP-style (round(512 x), clamped to
// 255) and packed four per u32. Dot products are exact integer sums
// (`dot4U8Packed`), so the k order no longer matters; scores convert to f32
// exactly (|score| < 2^24) and the top-2 logic is the f32 kernel's.
// Forward only: exact dot products make the swapped entry's forward top-2
// the reverse top-2 bit for bit, and with the cheap integer GEMM two
// forward passes beat the fused reverse epilogue (the reverse fields of
// `Entry` are ignored).''' + h[first:])


def reverse_epilogue(w):
    """Per-tile reverse partials of the fused cross-check (f32 kernel)."""
    w('''        if (want_rev) {
            // Column partials over this thread's 8 rows, then over the 16
            // row-threads (ty) of each column in shared memory.
''')
    for c in range(8):
        w('            {\n                var c = Top2(BIG, NONE, BIG, NONE);\n')
        for r in range(8):
            w(f'''                if ({ROWS[r]} < e.nq) {{
                    c = insert_inc(c, qn{r} - 2.0 * {dot(r, c)}, {ROWS[r]});
                }}
''')
        w(f'                store(({"64u + " if c >= 4 else ""}4u * tx + {c % 4}u) * 16u + ty, c);\n'
          '            }\n')
    w('''        }
        workgroupBarrier();
        // Two-level fold of the 16 row-thread partials of each column:
        // 2 threads x 8 partials, then 1 thread x 2.
        let fold_base = (t % 128u) * 16u + (t / 128u) * 8u;
        if (want_rev) {
            var c = Top2(BIG, NONE, BIG, NONE);
            for (var y = 0u; y < 8u; y = y + 1u) {
                c = fold(c, fold_base + y);
            }
            store(fold_base, c);
        }
        workgroupBarrier();
        if (want_rev && t < 128u && col0 + t < e.nt) {
            var c = Top2(BIG, NONE, BIG, NONE);
            c = fold(c, t * 16u);
            c = fold(c, t * 16u + 8u);
            rev_part[e.rev_part_off + wid.x * e.nt + col0 + t] =
                vec4<u32>(c.i1, bitcast<u32>(c.s1), bitcast<u32>(c.s2), c.i2);
        }
        workgroupBarrier();
''')


def top2_kernel():
    o = []
    w = o.append
    w('''
@compute @workgroup_size(256)
fn top2(@builtin(workgroup_id) wid: vec3<u32>, @builtin(local_invocation_id) lid: vec3<u32>) {
    let e = entries[wid.y];
    let row0 = wid.x * 128u;
    if (row0 >= e.nq) {
        return;
    }
    let t = lid.x;
    let tx = t % 16u;
    let ty = t / 16u;
    let nchunks = p.dim4 / 4u;
''')
    if not U8:
        w('    let want_rev = e.rev_out_off != NONE;\n')
    for r in range(8):
        w(f'''    var qn{r} = BIG;
    if ({ROWS[r]} < e.nq) {{
        qn{r} = norms[e.q_off + {ROWS[r]}];
    }}
    var r{r} = Top2(BIG, NONE, BIG, NONE);
''')
    w('''
    for (var col0 = 0u; col0 < e.nt; col0 = col0 + 128u) {
''')
    for r in range(8):
        w(f'        var acc{r}l = vec4<{ELEM}>({ZERO});\n        var acc{r}h = vec4<{ELEM}>({ZERO});\n')
    w('''        for (var kc = 0u; kc < nchunks; kc = kc + 1u) {
            put(true, t, 0u, fetch(e.q_off, e.nq, row0, kc, t, 0u));
            put(false, t, 0u, fetch(e.t_off, e.nt, col0, kc, t, 0u));
            put(true, t, 1u, fetch(e.q_off, e.nq, row0, kc, t, 1u));
            put(false, t, 1u, fetch(e.t_off, e.nt, col0, kc, t, 1u));
            workgroupBarrier();
''')
    for k in range(16):
        w(f'''            {{
                let al = qs[{k * 32}u + ty];
                let ah = qs[{k * 32 + 16}u + ty];
                let bl = ts[{k * 32}u + tx];
                let bh = ts[{k * 32 + 16}u + tx];
''')
        for r in range(8):
            if U8:
                for half in 'lh':
                    b = 'b' + half
                    dots = ', '.join(f'dot4U8Packed({A[r]}, {b}.{x})' for x in 'xyzw')
                    w(f'                acc{r}{half} = acc{r}{half} + vec4<u32>({dots});\n')
            else:
                w(f'                acc{r}l = acc{r}l + {A[r]} * bl;\n'
                  f'                acc{r}h = acc{r}h + {A[r]} * bh;\n')
        w('            }\n')
    w('''            workgroupBarrier();
        }
''')
    for c in range(8):
        w(f'''        {{
            let col = {COLS[c]};
            if (col < e.nt) {{
                let tn = norms[e.t_off + col];
''')
        for r in range(8):
            w(f'                r{r} = insert_inc(r{r}, tn - 2.0 * {dot(r, c)}, col);\n')
        w('            }\n        }\n')
    if not U8:
        reverse_epilogue(w)
    w('''    }

    // Reduce the 16 column-threads of each row: (row, tx) partials.
''')
    for r in range(8):
        w(f'    store(({"64u + " if r >= 4 else ""}4u * ty + {r % 4}u) * 16u + tx, r{r});\n')
    w('''    workgroupBarrier();
    if (t < 128u && row0 + t < e.nq) {
        var r = Top2(BIG, NONE, BIG, NONE);
        for (var x = 0u; x < 16u; x = x + 1u) {
            r = fold(r, t * 16u + x);
        }
        out[e.out_off + row0 + t] = vec4<u32>(r.i1, bitcast<u32>(r.s1), bitcast<u32>(r.s2), r.i2);
    }
}
''')
    return ''.join(o)


U8 = '--u8' in sys.argv[1:]
ELEM, ZERO = ('u32', '0u') if U8 else ('f32', '0.0')

if __name__ == '__main__':
    print((u8_header(HEADER) + top2_kernel()) if U8 else (HEADER + top2_kernel() + REV_REDUCE), end='')
